apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebula

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-api.yaml
  - service-api.yaml
  - hpa-api.yaml
  - pdb-api.yaml
