mod auth;
mod commands;
mod deep_link;
mod error;
mod types;

use tauri::Manager;
use tauri_plugin_deep_link::DeepLinkExt;
use tauri_specta::{collect_commands, Builder};

use commands::auth::{get_auth_state, sign_out, start_oauth};
use commands::connection::{get_connection, set_connection};

#[tauri::command]
#[specta::specta]
fn get_api_profile() -> String {
    std::env::var("NEBULA_API_PROFILE").unwrap_or_else(|_| "local".to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        get_api_profile,
        get_auth_state,
        start_oauth,
        sign_out,
        get_connection,
        set_connection,
    ]);

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// Auto-generated by tauri-specta — do not edit manually.\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_store::Builder::default().build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.show();
                let _ = window.set_focus();
            }
        }))
        .setup(|app| {
            #[cfg(any(windows, target_os = "linux"))]
            if let Err(err) = app.deep_link().register_all() {
                eprintln!("failed to register deep-link schemes: {err}");
            }

            let handle = app.handle().clone();
            app.deep_link().on_open_url(move |event| {
                let handle = handle.clone();
                let urls: Vec<String> = event.urls().iter().map(|u| u.to_string()).collect();
                tauri::async_runtime::spawn(async move {
                    for url in urls {
                        deep_link::handle(&url, &handle).await;
                    }
                });
            });

            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
