# https://github.com/crate-ci/typos/blob/master/docs/reference.md

[default.extend-words]
Hashi = "Hashi"
RTO = "RTO"

[files]
extend-exclude = [
  "target/",
  "*.lock",
  "CHANGELOG.md",
  "migrations/",
  "deny.toml",
  "skills-lock.json",
]
