//! Field definitions — consolidated enum (13 variants) + per-type structs + builders.
//!
//! Removed variants vs previous version: `Date`, `DateTime`, `Time`, `Color`, `Hidden`.
//! - Date-like fields → `StringField` with `hint: InputHint::{Date, DateTime, Time, Color}`.
//! - "Hidden" role → any field with `visible: VisibilityMode::Never`.

use nebula_validator::{Rule, ValueRule};
use serde::{Deserialize, Serialize};
use serde_json::{Number, Value};

use crate::{
    BooleanWidget, CodeWidget, FieldKey, FieldPath, InputHint, ListWidget, NumberWidget,
    ObjectWidget, RequiredMode, SecretWidget, SelectOption, SelectWidget, StringWidget,
    Transformer, VisibilityMode, error::ValidationError, mode::ExpressionMode,
};

// ── Macro ────────────────────────────────────────────────────────────────────

/// Generate a per-type field struct with shared base fields + type-specific extras.
///
/// Usage: `define_field!(TypeName { extra: Type = default, ... } expr: ExpressionMode::Xxx)`
///
/// Generated struct has all shared fields (key, label, description, placeholder, default,
/// visible, required, expression, group, rules, transformers) plus the extras. The generated
/// `impl` includes shared builders and a `key()` / `visible()` / `required()` / `expression()`
/// / `rules()` / `transformers()` / `default()` accessor set so structs can be used directly
/// before converting to `Field`.
macro_rules! define_field {
    ($name:ident { $($extra:ident: $ty:ty = $dflt:expr),* $(,)? } expr: $expr_dflt:expr) => {
        #[expect(missing_docs, reason = "type-specific fields are generated by macro")]
        #[non_exhaustive]
        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        pub struct $name {
            /// Stable field key.
            pub key: FieldKey,
            /// Human-readable label.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub label: Option<String>,
            /// Optional help text.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub description: Option<String>,
            /// Optional placeholder value.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub placeholder: Option<String>,
            /// Optional default JSON value.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub default: Option<Value>,
            /// Visibility mode.
            #[serde(default, skip_serializing_if = "VisibilityMode::is_default")]
            pub visible: VisibilityMode,
            /// Required mode.
            #[serde(default, skip_serializing_if = "RequiredMode::is_default")]
            pub required: RequiredMode,
            /// Expression mode.
            #[serde(default, skip_serializing_if = "ExpressionMode::is_default")]
            pub expression: ExpressionMode,
            /// Optional grouping name.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub group: Option<String>,
            /// Validation rules.
            #[serde(default, skip_serializing_if = "Vec::is_empty")]
            pub rules: Vec<Rule>,
            /// Runtime transformers.
            #[serde(default, skip_serializing_if = "Vec::is_empty")]
            pub transformers: Vec<Transformer>,
            // Type-specific fields.
            $(pub $extra: $ty,)*
        }

        impl $name {
            #[doc(hidden)]
            fn with_key(key: FieldKey) -> Self {
                Self {
                    key,
                    label: None,
                    description: None,
                    placeholder: None,
                    default: None,
                    visible: VisibilityMode::default(),
                    required: RequiredMode::default(),
                    expression: $expr_dflt,
                    group: None,
                    rules: Vec::new(),
                    transformers: Vec::new(),
                    $($extra: $dflt,)*
                }
            }

            /// Create a typed field with defaults.
            pub fn new(key: impl AsRef<str>) -> Self {
                Self::with_key(FieldKey::new(key).expect("field key must be valid"))
            }

            /// Borrow the field key.
            pub const fn key(&self) -> &FieldKey {
                &self.key
            }

            /// Set field label.
            #[must_use]
            pub fn label(mut self, value: impl Into<String>) -> Self {
                self.label = Some(value.into());
                self
            }

            /// Set field description.
            #[must_use]
            pub fn description(mut self, value: impl Into<String>) -> Self {
                self.description = Some(value.into());
                self
            }

            /// Set field placeholder.
            #[must_use]
            pub fn placeholder(mut self, value: impl Into<String>) -> Self {
                self.placeholder = Some(value.into());
                self
            }

            /// Set default JSON value (builder).
            #[must_use]
            pub fn default(mut self, value: Value) -> Self {
                self.default = Some(value);
                self
            }

            /// Set visibility mode directly (builder).
            ///
            /// Use this instead of the removed `HiddenField`:
            /// `.visible(VisibilityMode::Never)` hides a field.
            #[must_use]
            pub fn visible(mut self, mode: VisibilityMode) -> Self {
                self.visible = mode;
                self
            }

            /// Mark field visible when predicate holds.
            #[must_use]
            pub fn visible_when(mut self, rule: Rule) -> Self {
                self.visible = VisibilityMode::When(rule);
                self
            }

            /// Mark field as always required.
            ///
            /// `required` enforces more than presence: an empty string
            /// (String / Secret / Code / single File), an empty array
            /// (List, multi-Select, multi-File) and a JSON `null` all count
            /// as missing. This matches HTML-form `required` semantics —
            /// callers should not rely on `""` satisfying the constraint.
            #[must_use]
            pub fn required(mut self) -> Self {
                self.required = RequiredMode::Always;
                self
            }

            /// Mark field required when predicate holds.
            ///
            /// Emptiness rules mirror [`required`](Self::required): an
            /// empty collection / empty string / null value is treated as
            /// absent once the predicate fires.
            #[must_use]
            pub fn required_when(mut self, rule: Rule) -> Self {
                self.required = RequiredMode::When(rule);
                self
            }

            /// Mark field both visible and required when predicate holds.
            ///
            /// Shorthand for calling `visible_when(rule.clone())` +
            /// `required_when(rule)`. Prefer this over duplicating the rule
            /// in two setters.
            ///
            /// # Example
            ///
            /// ```ignore
            /// // `api_key` only appears and is only required when
            /// // `auth_type == "api_key"`.
            /// Field::secret(field_key!("api_key"))
            ///     .active_when(Rule::predicate(
            ///         Predicate::eq("auth_type", json!("api_key")).unwrap(),
            ///     ))
            /// ```
            #[must_use]
            pub fn active_when(mut self, rule: Rule) -> Self {
                self.visible = VisibilityMode::When(rule.clone());
                self.required = RequiredMode::When(rule);
                self
            }

            /// Set expression mode directly.
            #[must_use]
            pub const fn expression_mode(mut self, mode: ExpressionMode) -> Self {
                self.expression = mode;
                self
            }

            /// Forbid expression values on this field.
            #[must_use]
            pub const fn no_expression(mut self) -> Self {
                self.expression = ExpressionMode::Forbidden;
                self
            }

            /// Set grouping name.
            #[must_use]
            pub fn group(mut self, g: impl Into<String>) -> Self {
                self.group = Some(g.into());
                self
            }

            /// Append an arbitrary rule.
            #[must_use]
            pub fn with_rule(mut self, rule: Rule) -> Self {
                self.rules.push(rule);
                self
            }

            /// Append a runtime transformer.
            #[must_use]
            pub fn with_transformer(mut self, transformer: Transformer) -> Self {
                self.transformers.push(transformer);
                self
            }

            /// Finalize this typed field as enum wrapper.
            #[must_use]
            pub fn into_field(self) -> Field {
                self.into()
            }
        }
    };
}

// ── Per-type structs ─────────────────────────────────────────────────────────

define_field!(StringField {
    hint: InputHint = InputHint::default(),
    widget: StringWidget = StringWidget::Plain,
} expr: ExpressionMode::Allowed);

impl StringField {
    /// Set the input hint (replaces removed DateField/TimeField/ColorField).
    #[must_use]
    pub const fn hint(mut self, h: InputHint) -> Self {
        self.hint = h;
        self
    }

    /// Select widget variant.
    #[must_use]
    pub const fn widget(mut self, widget: StringWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Add a min-length rule.
    #[must_use]
    pub fn min_length(mut self, min: usize) -> Self {
        self.rules.push(Rule::min_length(min));
        self
    }

    /// Add a max-length rule.
    #[must_use]
    pub fn max_length(mut self, max: usize) -> Self {
        self.rules.push(Rule::max_length(max));
        self
    }

    /// Add a pattern rule.
    #[must_use]
    pub fn pattern(mut self, p: impl Into<String>) -> Self {
        self.rules.push(Rule::pattern(p));
        self
    }

    /// Add URL-format validation rule.
    #[must_use]
    pub fn url(mut self) -> Self {
        self.rules.push(Rule::url());
        self
    }

    /// Add email-format validation rule.
    #[must_use]
    pub fn email(mut self) -> Self {
        self.rules.push(Rule::email());
        self
    }
}

define_field!(SecretField {
    widget: SecretWidget = SecretWidget::Plain,
    reveal_last: Option<u8> = None,
    kdf: Option<crate::secret::KdfParams> = None,
} expr: ExpressionMode::Allowed);

impl SecretField {
    /// Select widget variant.
    #[must_use]
    pub const fn widget(mut self, widget: SecretWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Optional KDF: after resolution, replace the user string with a hashed
    /// [`crate::secret::SecretValue::Bytes`] (see [`crate::secret::KdfParams`]).
    #[must_use]
    pub fn kdf(mut self, params: crate::secret::KdfParams) -> Self {
        self.kdf = Some(params);
        self
    }

    /// Switch secret widget to multiline mode.
    #[must_use]
    pub const fn multiline(mut self) -> Self {
        self.widget = SecretWidget::Multiline;
        self
    }

    /// Add min-length validation rule.
    #[must_use]
    pub fn min_length(mut self, min: usize) -> Self {
        self.rules.push(Rule::min_length(min));
        self
    }

    /// Reveal the last N characters in masked displays.
    #[must_use]
    pub const fn reveal_last(mut self, chars: u8) -> Self {
        self.reveal_last = Some(chars);
        self
    }
}

define_field!(NumberField {
    integer: bool = false,
    widget: NumberWidget = NumberWidget::Plain,
    step: Option<Number> = None,
} expr: ExpressionMode::Allowed);

impl NumberField {
    /// Select widget variant.
    #[must_use]
    pub const fn widget(mut self, widget: NumberWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Switch number to integer mode.
    #[must_use]
    pub const fn integer(mut self) -> Self {
        self.integer = true;
        self
    }

    /// Add minimum numeric rule.
    #[must_use]
    pub fn min(mut self, min: impl Into<Number>) -> Self {
        self.rules.push(Rule::Value(ValueRule::Min(min.into())));
        self
    }

    /// Add maximum numeric rule.
    #[must_use]
    pub fn max(mut self, max: impl Into<Number>) -> Self {
        self.rules.push(Rule::Value(ValueRule::Max(max.into())));
        self
    }

    /// Set increment step.
    #[must_use]
    pub fn step(mut self, s: impl Into<Number>) -> Self {
        self.step = Some(s.into());
        self
    }
}

define_field!(BooleanField {
    widget: BooleanWidget = BooleanWidget::Toggle,
} expr: ExpressionMode::Forbidden);

impl BooleanField {
    /// Select widget variant.
    #[must_use]
    pub const fn widget(mut self, widget: BooleanWidget) -> Self {
        self.widget = widget;
        self
    }
}

define_field!(SelectField {
    options: Vec<SelectOption> = Vec::new(),
    dynamic: bool = false,
    loader: Option<String> = None,
    depends_on: Vec<FieldPath> = Vec::new(),
    multiple: bool = false,
    allow_custom: bool = false,
    searchable: bool = false,
    widget: SelectWidget = SelectWidget::Dropdown,
} expr: ExpressionMode::Forbidden);

impl SelectField {
    /// Select widget variant.
    #[must_use]
    pub const fn widget(mut self, widget: SelectWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Append static option.
    #[must_use]
    pub fn option(mut self, value: impl Into<Value>, label: impl Into<String>) -> Self {
        self.options.push(SelectOption::new(value.into(), label));
        self
    }

    /// Append many static options at once, typically from `HasSelectOptions::select_options`.
    #[must_use]
    pub fn extend_options(mut self, opts: impl IntoIterator<Item = SelectOption>) -> Self {
        self.options.extend(opts);
        self
    }

    /// Resolve options dynamically from a named loader.
    #[must_use]
    pub fn loader(mut self, loader_key: impl Into<String>) -> Self {
        self.dynamic = true;
        self.loader = Some(loader_key.into());
        self
    }

    /// Mark this field as dynamic without selecting a loader yet.
    #[must_use]
    pub const fn dynamic(mut self) -> Self {
        self.dynamic = true;
        self
    }

    /// Add a dependency path used as loader context.
    #[must_use]
    pub fn depends_on(mut self, path: impl Into<FieldPath>) -> Self {
        self.depends_on.push(path.into());
        self
    }

    /// Enable multi-select mode.
    #[must_use]
    pub const fn multiple(mut self) -> Self {
        self.multiple = true;
        self
    }

    /// Enable searchable UX.
    #[must_use]
    pub const fn searchable(mut self) -> Self {
        self.searchable = true;
        self
    }

    /// Allow values that are missing from static options.
    #[must_use]
    pub const fn allow_custom(mut self) -> Self {
        self.allow_custom = true;
        self
    }
}

define_field!(ObjectField {
    fields: Vec<Field> = Vec::new(),
    widget: ObjectWidget = ObjectWidget::Inline,
} expr: ExpressionMode::Allowed);

impl ObjectField {
    /// Select widget variant.
    #[must_use]
    pub const fn widget(mut self, widget: ObjectWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Append nested field.
    #[must_use]
    #[expect(
        clippy::should_implement_trait,
        reason = "builder API mirrors existing add-style schema DSL"
    )]
    pub fn add(mut self, field: impl Into<Field>) -> Self {
        self.fields.push(field.into());
        self
    }

    /// Append many nested fields at once.
    #[must_use]
    pub fn add_many<I, F>(mut self, fields: I) -> Self
    where
        I: IntoIterator<Item = F>,
        F: Into<Field>,
    {
        self.fields.extend(fields.into_iter().map(Into::into));
        self
    }
}

define_field!(ListField {
    item: Option<Box<Field>> = None,
    min_items: Option<u32> = None,
    max_items: Option<u32> = None,
    unique: bool = false,
    widget: ListWidget = ListWidget::Plain,
} expr: ExpressionMode::Allowed);

impl ListField {
    /// Select widget variant.
    #[must_use]
    pub const fn widget(mut self, widget: ListWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Set list item schema.
    #[must_use]
    pub fn item(mut self, item: impl Into<Field>) -> Self {
        self.item = Some(Box::new(item.into()));
        self
    }

    /// Set minimum item count.
    #[must_use]
    pub const fn min_items(mut self, count: u32) -> Self {
        self.min_items = Some(count);
        self
    }

    /// Set maximum item count.
    #[must_use]
    pub const fn max_items(mut self, count: u32) -> Self {
        self.max_items = Some(count);
        self
    }

    /// Require unique items.
    #[must_use]
    pub const fn unique(mut self) -> Self {
        self.unique = true;
        self
    }
}

define_field!(ModeField {
    variants: Vec<ModeVariant> = Vec::new(),
    default_variant: Option<String> = None,
    allow_dynamic_mode: bool = false,
} expr: ExpressionMode::Allowed);

/// Variant definition for mode fields.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModeVariant {
    /// Variant key.
    pub key: String,
    /// Variant label.
    pub label: String,
    /// Variant payload schema.
    pub field: Box<Field>,
}

impl ModeField {
    /// Append variant.
    #[must_use]
    pub fn variant(
        mut self,
        key: impl Into<String>,
        label: impl Into<String>,
        field: impl Into<Field>,
    ) -> Self {
        self.variants.push(ModeVariant {
            key: key.into(),
            label: label.into(),
            field: Box::new(field.into()),
        });
        self
    }

    /// Set default variant key.
    #[must_use]
    pub fn default_variant(mut self, key: impl Into<String>) -> Self {
        self.default_variant = Some(key.into());
        self
    }

    /// Allow the mode to be selected dynamically at runtime.
    #[must_use]
    pub const fn allow_dynamic_mode(mut self) -> Self {
        self.allow_dynamic_mode = true;
        self
    }
}

define_field!(CodeField {
    language: String = "plaintext".to_owned(),
    widget: CodeWidget = CodeWidget::Monaco,
} expr: ExpressionMode::Allowed);

impl CodeField {
    /// Set language identifier.
    #[must_use]
    pub fn language(mut self, l: impl Into<String>) -> Self {
        self.language = l.into();
        self
    }

    /// Select widget variant.
    #[must_use]
    pub const fn widget(mut self, widget: CodeWidget) -> Self {
        self.widget = widget;
        self
    }
}

define_field!(FileField {
    accept: Option<String> = None,
    max_size: Option<u64> = None,
    multiple: bool = false,
} expr: ExpressionMode::Allowed);

impl FileField {
    /// Limit accepted file MIME patterns.
    #[must_use]
    pub fn accept(mut self, mime: impl Into<String>) -> Self {
        self.accept = Some(mime.into());
        self
    }

    /// Set maximum file size in bytes.
    #[must_use]
    pub const fn max_size(mut self, bytes: u64) -> Self {
        self.max_size = Some(bytes);
        self
    }

    /// Enable multi-file selection mode.
    #[must_use]
    pub const fn multiple(mut self) -> Self {
        self.multiple = true;
        self
    }
}

define_field!(ComputedField {
    expression_source: String = String::new(),
    returns: ComputedReturn = ComputedReturn::String,
} expr: ExpressionMode::Required);

/// Return-type hint for computed fields.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ComputedReturn {
    /// Expression returns string.
    String,
    /// Expression returns number.
    Number,
    /// Expression returns boolean.
    Boolean,
}

impl ComputedField {
    /// Set the expression source code.
    #[must_use]
    pub fn expression_source(mut self, src: impl Into<String>) -> Self {
        self.expression_source = src.into();
        self
    }

    /// Set the return type hint.
    #[must_use]
    pub const fn returns(mut self, r: ComputedReturn) -> Self {
        self.returns = r;
        self
    }
}

define_field!(DynamicField {
    depends_on: Vec<FieldPath> = Vec::new(),
    loader: Option<String> = None,
} expr: ExpressionMode::Allowed);

impl DynamicField {
    /// Resolve payload from a named loader.
    #[must_use]
    pub fn loader(mut self, loader_key: impl Into<String>) -> Self {
        self.loader = Some(loader_key.into());
        self
    }

    /// Add a dependency path used as loader context.
    #[must_use]
    pub fn depends_on(mut self, path: impl Into<FieldPath>) -> Self {
        self.depends_on.push(path.into());
        self
    }
}

define_field!(NoticeField {
    severity: NoticeSeverity = NoticeSeverity::Info,
} expr: ExpressionMode::Forbidden);

/// Severity level for notice field rendering.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NoticeSeverity {
    /// Informational notice.
    #[default]
    Info,
    /// Warning notice.
    Warning,
    /// Danger notice.
    Danger,
    /// Success notice.
    Success,
}

// ── Top-level Field enum ──────────────────────────────────────────────────────

/// Enum wrapper for typed schema fields (13 variants).
///
/// Removed in this version: `Date`, `DateTime`, `Time`, `Color`, `Hidden`.
/// - Date-like: use `Field::string(k).hint(InputHint::Date)` etc.
/// - Hidden: use `.visible(VisibilityMode::Never)` on any field.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Field {
    /// String field (replaces Date/DateTime/Time/Color via `hint`).
    String(StringField),
    /// Secret string field.
    Secret(SecretField),
    /// Numeric field.
    Number(NumberField),
    /// Boolean field.
    Boolean(BooleanField),
    /// Select field.
    Select(SelectField),
    /// Object field.
    Object(ObjectField),
    /// List field.
    List(ListField),
    /// Mode field.
    Mode(ModeField),
    /// Code field.
    Code(CodeField),
    /// File field.
    File(FileField),
    /// Computed field (expression always required).
    Computed(ComputedField),
    /// Dynamic field (schema resolved at runtime via loader).
    Dynamic(DynamicField),
    /// Notice/info field (display-only).
    Notice(NoticeField),
}

const REQUIRED_EXPRESSION_MODE: ExpressionMode = ExpressionMode::Required;
const FORBIDDEN_EXPRESSION_MODE: ExpressionMode = ExpressionMode::Forbidden;

// ── Factory methods ───────────────────────────────────────────────────────────

impl Field {
    #[expect(
        clippy::result_large_err,
        reason = "ValidationError is intentionally large; field creation is on the authoring path"
    )]
    fn parse_key_or_error(key: &str) -> Result<FieldKey, ValidationError> {
        FieldKey::new(key).map_err(|err| {
            ValidationError::builder("invalid_key")
                .at(FieldPath::root())
                .param("key", Value::String(key.to_owned()))
                .message(format!("invalid key `{key}`: {err}"))
                .build()
        })
    }

    /// Create a [`StringField`] with the given key.
    ///
    /// # Example
    ///
    /// ```rust
    /// use nebula_schema::{Field, Schema, field_key};
    ///
    /// let schema = Schema::builder()
    ///     .add(Field::string(field_key!("greeting")).required())
    ///     .build()
    ///     .unwrap();
    /// assert!(schema.find(&field_key!("greeting")).is_some());
    /// ```
    #[must_use]
    pub fn string(key: impl AsRef<str>) -> StringField {
        StringField::new(key)
    }

    /// Fallible variant of [`Field::string`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_string(key: impl AsRef<str>) -> Result<StringField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(StringField::with_key(key))
    }

    /// Create `SecretField`.
    #[must_use]
    pub fn secret(key: impl AsRef<str>) -> SecretField {
        SecretField::new(key)
    }

    /// Fallible variant of [`Field::secret`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_secret(key: impl AsRef<str>) -> Result<SecretField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(SecretField::with_key(key))
    }

    /// Create `NumberField`.
    #[must_use]
    pub fn number(key: impl AsRef<str>) -> NumberField {
        NumberField::new(key)
    }

    /// Fallible variant of [`Field::number`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_number(key: impl AsRef<str>) -> Result<NumberField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(NumberField::with_key(key))
    }

    /// Create integer `NumberField`.
    #[must_use]
    pub fn integer(key: impl AsRef<str>) -> NumberField {
        NumberField::new(key).integer()
    }

    /// Fallible variant of [`Field::integer`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_integer(key: impl AsRef<str>) -> Result<NumberField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(NumberField::with_key(key).integer())
    }

    /// Create a [`BooleanField`] with the given key.
    ///
    /// Boolean fields forbid expression values by default.
    ///
    /// # Example
    ///
    /// ```rust
    /// use nebula_schema::{Field, FieldValues, Schema, field_key};
    /// use serde_json::json;
    ///
    /// let schema = Schema::builder()
    ///     .add(Field::boolean(field_key!("enabled")))
    ///     .build()
    ///     .unwrap();
    ///
    /// let values = FieldValues::from_json(json!({"enabled": false})).unwrap();
    /// assert!(schema.validate(&values).is_ok());
    /// ```
    #[must_use]
    pub fn boolean(key: impl AsRef<str>) -> BooleanField {
        BooleanField::new(key)
    }

    /// Fallible variant of [`Field::boolean`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_boolean(key: impl AsRef<str>) -> Result<BooleanField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(BooleanField::with_key(key))
    }

    /// Create `SelectField`.
    #[must_use]
    pub fn select(key: impl AsRef<str>) -> SelectField {
        SelectField::new(key)
    }

    /// Fallible variant of [`Field::select`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_select(key: impl AsRef<str>) -> Result<SelectField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(SelectField::with_key(key))
    }

    /// Create `ObjectField`.
    #[must_use]
    pub fn object(key: impl AsRef<str>) -> ObjectField {
        ObjectField::new(key)
    }

    /// Fallible variant of [`Field::object`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_object(key: impl AsRef<str>) -> Result<ObjectField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(ObjectField::with_key(key))
    }

    /// Create `ListField`.
    #[must_use]
    pub fn list(key: impl AsRef<str>) -> ListField {
        ListField::new(key)
    }

    /// Fallible variant of [`Field::list`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_list(key: impl AsRef<str>) -> Result<ListField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(ListField::with_key(key))
    }

    /// Create `ModeField`.
    #[must_use]
    pub fn mode(key: impl AsRef<str>) -> ModeField {
        ModeField::new(key)
    }

    /// Fallible variant of [`Field::mode`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_mode(key: impl AsRef<str>) -> Result<ModeField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(ModeField::with_key(key))
    }

    /// Create `CodeField`.
    #[must_use]
    pub fn code(key: impl AsRef<str>) -> CodeField {
        CodeField::new(key)
    }

    /// Fallible variant of [`Field::code`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_code(key: impl AsRef<str>) -> Result<CodeField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(CodeField::with_key(key))
    }

    /// Create `FileField`.
    #[must_use]
    pub fn file(key: impl AsRef<str>) -> FileField {
        FileField::new(key)
    }

    /// Fallible variant of [`Field::file`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_file(key: impl AsRef<str>) -> Result<FileField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(FileField::with_key(key))
    }

    /// Create `ComputedField`.
    #[must_use]
    pub fn computed(key: impl AsRef<str>) -> ComputedField {
        ComputedField::new(key)
    }

    /// Fallible variant of [`Field::computed`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_computed(key: impl AsRef<str>) -> Result<ComputedField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(ComputedField::with_key(key))
    }

    /// Create `DynamicField`.
    #[must_use]
    pub fn dynamic(key: impl AsRef<str>) -> DynamicField {
        DynamicField::new(key)
    }

    /// Fallible variant of [`Field::dynamic`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_dynamic(key: impl AsRef<str>) -> Result<DynamicField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(DynamicField::with_key(key))
    }

    /// Create `NoticeField`.
    #[must_use]
    pub fn notice(key: impl AsRef<str>) -> NoticeField {
        NoticeField::new(key)
    }

    /// Fallible variant of [`Field::notice`] for runtime-provided keys.
    ///
    /// # Errors
    ///
    /// Returns `invalid_key` when `key` cannot be parsed into a [`FieldKey`].
    #[allow(clippy::result_large_err)]
    pub fn try_notice(key: impl AsRef<str>) -> Result<NoticeField, ValidationError> {
        let key = Self::parse_key_or_error(key.as_ref())?;
        Ok(NoticeField::with_key(key))
    }
}

// ── Shared accessors ──────────────────────────────────────────────────────────

impl Field {
    /// Shared key accessor.
    #[inline]
    #[must_use]
    pub const fn key(&self) -> &FieldKey {
        match self {
            Self::String(f) => &f.key,
            Self::Secret(f) => &f.key,
            Self::Number(f) => &f.key,
            Self::Boolean(f) => &f.key,
            Self::Select(f) => &f.key,
            Self::Object(f) => &f.key,
            Self::List(f) => &f.key,
            Self::Mode(f) => &f.key,
            Self::Code(f) => &f.key,
            Self::File(f) => &f.key,
            Self::Computed(f) => &f.key,
            Self::Dynamic(f) => &f.key,
            Self::Notice(f) => &f.key,
        }
    }

    /// Shared visibility accessor.
    #[inline]
    #[must_use]
    pub const fn visible(&self) -> &VisibilityMode {
        match self {
            Self::String(f) => &f.visible,
            Self::Secret(f) => &f.visible,
            Self::Number(f) => &f.visible,
            Self::Boolean(f) => &f.visible,
            Self::Select(f) => &f.visible,
            Self::Object(f) => &f.visible,
            Self::List(f) => &f.visible,
            Self::Mode(f) => &f.visible,
            Self::Code(f) => &f.visible,
            Self::File(f) => &f.visible,
            Self::Computed(f) => &f.visible,
            Self::Dynamic(f) => &f.visible,
            Self::Notice(f) => &f.visible,
        }
    }

    /// Shared required accessor.
    #[inline]
    #[must_use]
    pub const fn required(&self) -> &RequiredMode {
        match self {
            Self::String(f) => &f.required,
            Self::Secret(f) => &f.required,
            Self::Number(f) => &f.required,
            Self::Boolean(f) => &f.required,
            Self::Select(f) => &f.required,
            Self::Object(f) => &f.required,
            Self::List(f) => &f.required,
            Self::Mode(f) => &f.required,
            Self::Code(f) => &f.required,
            Self::File(f) => &f.required,
            Self::Computed(f) => &f.required,
            Self::Dynamic(f) => &f.required,
            Self::Notice(f) => &f.required,
        }
    }

    /// Shared expression mode accessor.
    #[inline]
    #[must_use]
    pub const fn expression(&self) -> &ExpressionMode {
        match self {
            Self::String(f) => &f.expression,
            Self::Secret(f) => &f.expression,
            Self::Number(f) => &f.expression,
            Self::Boolean(f) => &f.expression,
            Self::Select(f) => &f.expression,
            Self::Object(f) => &f.expression,
            Self::List(f) => &f.expression,
            Self::Mode(f) => &f.expression,
            Self::Code(f) => &f.expression,
            Self::File(f) => &f.expression,
            Self::Computed(_) => &REQUIRED_EXPRESSION_MODE,
            Self::Dynamic(f) => &f.expression,
            Self::Notice(_) => &FORBIDDEN_EXPRESSION_MODE,
        }
    }

    /// Shared rules accessor.
    #[inline]
    #[must_use]
    pub const fn rules(&self) -> &[Rule] {
        match self {
            Self::String(f) => f.rules.as_slice(),
            Self::Secret(f) => f.rules.as_slice(),
            Self::Number(f) => f.rules.as_slice(),
            Self::Boolean(f) => f.rules.as_slice(),
            Self::Select(f) => f.rules.as_slice(),
            Self::Object(f) => f.rules.as_slice(),
            Self::List(f) => f.rules.as_slice(),
            Self::Mode(f) => f.rules.as_slice(),
            Self::Code(f) => f.rules.as_slice(),
            Self::File(f) => f.rules.as_slice(),
            Self::Computed(f) => f.rules.as_slice(),
            Self::Dynamic(f) => f.rules.as_slice(),
            Self::Notice(f) => f.rules.as_slice(),
        }
    }

    /// Shared transformer accessor.
    #[inline]
    #[must_use]
    pub const fn transformers(&self) -> &[Transformer] {
        match self {
            Self::String(f) => f.transformers.as_slice(),
            Self::Secret(f) => f.transformers.as_slice(),
            Self::Number(f) => f.transformers.as_slice(),
            Self::Boolean(f) => f.transformers.as_slice(),
            Self::Select(f) => f.transformers.as_slice(),
            Self::Object(f) => f.transformers.as_slice(),
            Self::List(f) => f.transformers.as_slice(),
            Self::Mode(f) => f.transformers.as_slice(),
            Self::Code(f) => f.transformers.as_slice(),
            Self::File(f) => f.transformers.as_slice(),
            Self::Computed(f) => f.transformers.as_slice(),
            Self::Dynamic(f) => f.transformers.as_slice(),
            Self::Notice(f) => f.transformers.as_slice(),
        }
    }

    /// Shared default-value accessor.
    #[inline]
    #[must_use]
    pub const fn default(&self) -> Option<&Value> {
        match self {
            Self::String(f) => f.default.as_ref(),
            Self::Secret(f) => f.default.as_ref(),
            Self::Number(f) => f.default.as_ref(),
            Self::Boolean(f) => f.default.as_ref(),
            Self::Select(f) => f.default.as_ref(),
            Self::Object(f) => f.default.as_ref(),
            Self::List(f) => f.default.as_ref(),
            Self::Mode(f) => f.default.as_ref(),
            Self::Code(f) => f.default.as_ref(),
            Self::File(f) => f.default.as_ref(),
            Self::Computed(f) => f.default.as_ref(),
            Self::Dynamic(f) => f.default.as_ref(),
            Self::Notice(f) => f.default.as_ref(),
        }
    }

    /// Return the static type name for error messages and diagnostics.
    #[inline]
    #[must_use]
    pub const fn type_name(&self) -> &'static str {
        match self {
            Self::String(_) => "string",
            Self::Secret(_) => "secret",
            Self::Number(_) => "number",
            Self::Boolean(_) => "boolean",
            Self::Select(_) => "select",
            Self::Object(_) => "object",
            Self::List(_) => "list",
            Self::Mode(_) => "mode",
            Self::Code(_) => "code",
            Self::File(_) => "file",
            Self::Computed(_) => "computed",
            Self::Dynamic(_) => "dynamic",
            Self::Notice(_) => "notice",
        }
    }
}

// ── From impls ────────────────────────────────────────────────────────────────

impl From<StringField> for Field {
    fn from(value: StringField) -> Self {
        Self::String(value)
    }
}

impl From<SecretField> for Field {
    fn from(value: SecretField) -> Self {
        Self::Secret(value)
    }
}

impl From<NumberField> for Field {
    fn from(value: NumberField) -> Self {
        Self::Number(value)
    }
}

impl From<BooleanField> for Field {
    fn from(value: BooleanField) -> Self {
        Self::Boolean(value)
    }
}

impl From<SelectField> for Field {
    fn from(value: SelectField) -> Self {
        Self::Select(value)
    }
}

impl From<ObjectField> for Field {
    fn from(value: ObjectField) -> Self {
        Self::Object(value)
    }
}

impl From<ListField> for Field {
    fn from(value: ListField) -> Self {
        Self::List(value)
    }
}

impl From<ModeField> for Field {
    fn from(value: ModeField) -> Self {
        Self::Mode(value)
    }
}

impl From<CodeField> for Field {
    fn from(value: CodeField) -> Self {
        Self::Code(value)
    }
}

impl From<FileField> for Field {
    fn from(value: FileField) -> Self {
        Self::File(value)
    }
}

impl From<ComputedField> for Field {
    fn from(mut value: ComputedField) -> Self {
        // `ComputedField` is expression-backed by design; keep this invariant
        // even if generic builder helpers changed the mode.
        value.expression = ExpressionMode::Required;
        Self::Computed(value)
    }
}

impl From<DynamicField> for Field {
    fn from(value: DynamicField) -> Self {
        Self::Dynamic(value)
    }
}

impl From<NoticeField> for Field {
    fn from(mut value: NoticeField) -> Self {
        // `NoticeField` is display-only and must never accept expressions.
        value.expression = ExpressionMode::Forbidden;
        Self::Notice(value)
    }
}
