use nebula_validator::Rule;
use serde::{Deserialize, Serialize};
use serde_json::{Number, Value};

use crate::{
    BooleanWidget, CodeWidget, FieldKey, FieldPath, ListWidget, NumberWidget, ObjectWidget,
    RequiredMode, SecretWidget, SelectOption, SelectWidget, StringWidget, Transformer,
    VisibilityMode,
};

macro_rules! define_field {
    ($name:ident { $($field:ident: $type:ty = $default:expr),* $(,)? }) => {
        #[allow(missing_docs, reason = "type-specific fields are generated by macro")]
        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        pub struct $name {
            /// Stable field key.
            pub key: FieldKey,
            /// Human-readable label.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub label: Option<String>,
            /// Optional help text.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub description: Option<String>,
            /// Optional placeholder value.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub placeholder: Option<String>,
            /// Optional UI hint.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub hint: Option<String>,
            /// Optional default JSON value.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub default: Option<Value>,
            /// Visibility mode.
            #[serde(default, skip_serializing_if = "VisibilityMode::is_default")]
            pub visible: VisibilityMode,
            /// Required mode.
            #[serde(default, skip_serializing_if = "RequiredMode::is_default")]
            pub required: RequiredMode,
            /// Optional grouping name.
            #[serde(default, skip_serializing_if = "Option::is_none")]
            pub group: Option<String>,
            /// Validation rules.
            #[serde(default, skip_serializing_if = "Vec::is_empty")]
            pub rules: Vec<Rule>,
            /// Runtime transformers.
            #[serde(default, skip_serializing_if = "Vec::is_empty")]
            pub transformers: Vec<Transformer>,
            // Type-specific fields.
            $(pub $field: $type,)*
        }

        impl $name {
            /// Create a typed field with defaults.
            pub fn new(key: impl Into<FieldKey>) -> Self {
                Self {
                    key: key.into(),
                    label: None,
                    description: None,
                    placeholder: None,
                    hint: None,
                    default: None,
                    visible: VisibilityMode::default(),
                    required: RequiredMode::default(),
                    group: None,
                    rules: Vec::new(),
                    transformers: Vec::new(),
                    $($field: $default,)*
                }
            }

            /// Set field label.
            #[must_use]
            pub fn label(mut self, value: impl Into<String>) -> Self {
                self.label = Some(value.into());
                self
            }

            /// Set field description.
            #[must_use]
            pub fn description(mut self, value: impl Into<String>) -> Self {
                self.description = Some(value.into());
                self
            }

            /// Set field placeholder.
            #[must_use]
            pub fn placeholder(mut self, value: impl Into<String>) -> Self {
                self.placeholder = Some(value.into());
                self
            }

            /// Set default JSON value.
            #[must_use]
            pub fn default(mut self, value: Value) -> Self {
                self.default = Some(value);
                self
            }

            /// Mark field as always required.
            #[must_use]
            pub fn required(mut self) -> Self {
                self.required = RequiredMode::Always;
                self
            }

            /// Mark field required when predicate holds.
            #[must_use]
            pub fn required_when(mut self, rule: Rule) -> Self {
                self.required = RequiredMode::When(rule);
                self
            }

            /// Mark field visible when predicate holds.
            #[must_use]
            pub fn visible_when(mut self, rule: Rule) -> Self {
                self.visible = VisibilityMode::When(rule);
                self
            }

            /// Mark field visible and required when predicate holds.
            #[must_use]
            pub fn active_when(mut self, rule: Rule) -> Self {
                self.visible = VisibilityMode::When(rule.clone());
                self.required = RequiredMode::When(rule);
                self
            }

            /// Append an arbitrary rule.
            #[must_use]
            pub fn with_rule(mut self, rule: Rule) -> Self {
                self.rules.push(rule);
                self
            }

            /// Finalize this typed field as enum wrapper.
            #[must_use]
            pub fn into_field(self) -> Field {
                self.into()
            }
        }
    };
}

define_field!(StringField {
    widget: StringWidget = StringWidget::Plain,
});

impl StringField {
    /// Select widget variant.
    #[must_use]
    pub fn widget(mut self, widget: StringWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Add a min-length rule.
    #[must_use]
    pub fn min_length(mut self, min: usize) -> Self {
        self.rules.push(Rule::MinLength { min, message: None });
        self
    }

    /// Add a max-length rule.
    #[must_use]
    pub fn max_length(mut self, max: usize) -> Self {
        self.rules.push(Rule::MaxLength { max, message: None });
        self
    }

    /// Add URL-format validation rule.
    #[must_use]
    pub fn url(mut self) -> Self {
        self.rules.push(Rule::Url { message: None });
        self
    }
}

define_field!(SecretField {
    widget: SecretWidget = SecretWidget::Plain,
    reveal_last: Option<u8> = None,
});

impl SecretField {
    /// Select widget variant.
    #[must_use]
    pub fn widget(mut self, widget: SecretWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Switch secret widget to multiline mode.
    #[must_use]
    pub fn multiline(mut self) -> Self {
        self.widget = SecretWidget::Multiline;
        self
    }

    /// Add min-length validation rule.
    #[must_use]
    pub fn min_length(mut self, min: usize) -> Self {
        self.rules.push(Rule::MinLength { min, message: None });
        self
    }

    /// Reveal the last N characters in masked displays.
    #[must_use]
    pub fn reveal_last(mut self, chars: u8) -> Self {
        self.reveal_last = Some(chars);
        self
    }
}

define_field!(NumberField {
    integer: bool = false,
    widget: NumberWidget = NumberWidget::Plain,
    step: Option<Number> = None,
});

impl NumberField {
    /// Select widget variant.
    #[must_use]
    pub fn widget(mut self, widget: NumberWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Switch number to integer mode.
    #[must_use]
    pub fn integer(mut self) -> Self {
        self.integer = true;
        self
    }

    /// Add minimum numeric rule.
    #[must_use]
    pub fn min(mut self, min: impl Into<Number>) -> Self {
        self.rules.push(Rule::Min {
            min: min.into(),
            message: None,
        });
        self
    }

    /// Add maximum numeric rule.
    #[must_use]
    pub fn max(mut self, max: impl Into<Number>) -> Self {
        self.rules.push(Rule::Max {
            max: max.into(),
            message: None,
        });
        self
    }
}

define_field!(BooleanField {
    widget: BooleanWidget = BooleanWidget::Toggle,
});

impl BooleanField {
    /// Select widget variant.
    #[must_use]
    pub fn widget(mut self, widget: BooleanWidget) -> Self {
        self.widget = widget;
        self
    }
}

define_field!(SelectField {
    options: Vec<SelectOption> = Vec::new(),
    dynamic: bool = false,
    depends_on: Vec<FieldPath> = Vec::new(),
    multiple: bool = false,
    allow_custom: bool = false,
    searchable: bool = false,
    widget: SelectWidget = SelectWidget::Dropdown,
});

impl SelectField {
    /// Select widget variant.
    #[must_use]
    pub fn widget(mut self, widget: SelectWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Append static option.
    #[must_use]
    pub fn option(mut self, value: impl Into<Value>, label: impl Into<String>) -> Self {
        self.options.push(SelectOption::new(value.into(), label));
        self
    }

    /// Enable multi-select mode.
    #[must_use]
    pub fn multiple(mut self) -> Self {
        self.multiple = true;
        self
    }

    /// Enable searchable UX.
    #[must_use]
    pub fn searchable(mut self) -> Self {
        self.searchable = true;
        self
    }
}

define_field!(ObjectField {
    fields: Vec<Field> = Vec::new(),
    widget: ObjectWidget = ObjectWidget::Inline,
});

impl ObjectField {
    /// Select widget variant.
    #[must_use]
    pub fn widget(mut self, widget: ObjectWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Append nested field.
    #[must_use]
    #[expect(
        clippy::should_implement_trait,
        reason = "builder API mirrors existing add-style schema DSL"
    )]
    pub fn add(mut self, field: impl Into<Field>) -> Self {
        self.fields.push(field.into());
        self
    }
}

define_field!(ListField {
    item: Option<Box<Field>> = None,
    min_items: Option<u32> = None,
    max_items: Option<u32> = None,
    unique: bool = false,
    widget: ListWidget = ListWidget::Plain,
});

impl ListField {
    /// Select widget variant.
    #[must_use]
    pub fn widget(mut self, widget: ListWidget) -> Self {
        self.widget = widget;
        self
    }

    /// Set list item schema.
    #[must_use]
    pub fn item(mut self, item: impl Into<Field>) -> Self {
        self.item = Some(Box::new(item.into()));
        self
    }

    /// Set minimum item count.
    #[must_use]
    pub fn min_items(mut self, count: u32) -> Self {
        self.min_items = Some(count);
        self
    }

    /// Set maximum item count.
    #[must_use]
    pub fn max_items(mut self, count: u32) -> Self {
        self.max_items = Some(count);
        self
    }
}

define_field!(ModeField {
    variants: Vec<ModeVariant> = Vec::new(),
    default_variant: Option<String> = None,
});

/// Variant definition for mode fields.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModeVariant {
    /// Variant key.
    pub key: String,
    /// Variant label.
    pub label: String,
    /// Variant payload schema.
    pub field: Box<Field>,
}

impl ModeField {
    /// Append variant.
    #[must_use]
    pub fn variant(
        mut self,
        key: impl Into<String>,
        label: impl Into<String>,
        field: impl Into<Field>,
    ) -> Self {
        self.variants.push(ModeVariant {
            key: key.into(),
            label: label.into(),
            field: Box::new(field.into()),
        });
        self
    }

    /// Set default variant key.
    #[must_use]
    pub fn default_variant(mut self, key: impl Into<String>) -> Self {
        self.default_variant = Some(key.into());
        self
    }
}

define_field!(CodeField {
    language: String = "plaintext".to_owned(),
    widget: CodeWidget = CodeWidget::Monaco,
});

impl CodeField {
    /// Select widget variant.
    #[must_use]
    pub fn widget(mut self, widget: CodeWidget) -> Self {
        self.widget = widget;
        self
    }
}

define_field!(DateField {});
define_field!(DateTimeField {});
define_field!(TimeField {});
define_field!(ColorField {});

define_field!(FileField {
    accept: Option<String> = None,
    max_size: Option<u64> = None,
    multiple: bool = false,
});

define_field!(HiddenField {});

define_field!(ComputedField {
    expression: String = String::new(),
    returns: ComputedReturn = ComputedReturn::String,
});

/// Return-type hint for computed fields.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ComputedReturn {
    /// Expression returns string.
    String,
    /// Expression returns number.
    Number,
    /// Expression returns boolean.
    Boolean,
}

define_field!(DynamicField {
    depends_on: Vec<FieldPath> = Vec::new(),
});

define_field!(NoticeField {
    severity: NoticeSeverity = NoticeSeverity::Info,
});

/// Severity level for notice field rendering.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NoticeSeverity {
    /// Informational notice.
    #[default]
    Info,
    /// Warning notice.
    Warning,
    /// Danger notice.
    Danger,
    /// Success notice.
    Success,
}

/// Enum wrapper for typed schema fields.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Field {
    /// String field.
    String(StringField),
    /// Secret string field.
    Secret(SecretField),
    /// Numeric field.
    Number(NumberField),
    /// Boolean field.
    Boolean(BooleanField),
    /// Select field.
    Select(SelectField),
    /// Object field.
    Object(ObjectField),
    /// List field.
    List(ListField),
    /// Mode field.
    Mode(ModeField),
    /// Code field.
    Code(CodeField),
    /// Date field.
    Date(DateField),
    /// Date-time field.
    DateTime(DateTimeField),
    /// Time field.
    Time(TimeField),
    /// Color field.
    Color(ColorField),
    /// File field.
    File(FileField),
    /// Hidden field.
    Hidden(HiddenField),
    /// Computed field.
    Computed(ComputedField),
    /// Dynamic field.
    Dynamic(DynamicField),
    /// Notice field.
    Notice(NoticeField),
}

impl Field {
    /// Create `StringField`.
    pub fn string(key: impl Into<FieldKey>) -> StringField {
        StringField::new(key)
    }

    /// Create `SecretField`.
    pub fn secret(key: impl Into<FieldKey>) -> SecretField {
        SecretField::new(key)
    }

    /// Create `NumberField`.
    pub fn number(key: impl Into<FieldKey>) -> NumberField {
        NumberField::new(key)
    }

    /// Create integer `NumberField`.
    pub fn integer(key: impl Into<FieldKey>) -> NumberField {
        NumberField::new(key).integer()
    }

    /// Create `BooleanField`.
    pub fn boolean(key: impl Into<FieldKey>) -> BooleanField {
        BooleanField::new(key)
    }

    /// Create `SelectField`.
    pub fn select(key: impl Into<FieldKey>) -> SelectField {
        SelectField::new(key)
    }

    /// Create `ObjectField`.
    pub fn object(key: impl Into<FieldKey>) -> ObjectField {
        ObjectField::new(key)
    }

    /// Create `ListField`.
    pub fn list(key: impl Into<FieldKey>) -> ListField {
        ListField::new(key)
    }

    /// Create `ModeField`.
    pub fn mode(key: impl Into<FieldKey>) -> ModeField {
        ModeField::new(key)
    }

    /// Create `CodeField`.
    pub fn code(key: impl Into<FieldKey>) -> CodeField {
        CodeField::new(key)
    }

    /// Create `DateField`.
    pub fn date(key: impl Into<FieldKey>) -> DateField {
        DateField::new(key)
    }

    /// Create `DateTimeField`.
    pub fn datetime(key: impl Into<FieldKey>) -> DateTimeField {
        DateTimeField::new(key)
    }

    /// Create `TimeField`.
    pub fn time(key: impl Into<FieldKey>) -> TimeField {
        TimeField::new(key)
    }

    /// Create `ColorField`.
    pub fn color(key: impl Into<FieldKey>) -> ColorField {
        ColorField::new(key)
    }

    /// Create `FileField`.
    pub fn file(key: impl Into<FieldKey>) -> FileField {
        FileField::new(key)
    }

    /// Create `HiddenField`.
    pub fn hidden(key: impl Into<FieldKey>) -> HiddenField {
        HiddenField::new(key)
    }

    /// Create `ComputedField`.
    pub fn computed(key: impl Into<FieldKey>) -> ComputedField {
        ComputedField::new(key)
    }

    /// Create `DynamicField`.
    pub fn dynamic(key: impl Into<FieldKey>) -> DynamicField {
        DynamicField::new(key)
    }

    /// Create `NoticeField`.
    pub fn notice(key: impl Into<FieldKey>) -> NoticeField {
        NoticeField::new(key)
    }

    /// Shared key accessor.
    pub fn key(&self) -> &FieldKey {
        match self {
            Self::String(field) => &field.key,
            Self::Secret(field) => &field.key,
            Self::Number(field) => &field.key,
            Self::Boolean(field) => &field.key,
            Self::Select(field) => &field.key,
            Self::Object(field) => &field.key,
            Self::List(field) => &field.key,
            Self::Mode(field) => &field.key,
            Self::Code(field) => &field.key,
            Self::Date(field) => &field.key,
            Self::DateTime(field) => &field.key,
            Self::Time(field) => &field.key,
            Self::Color(field) => &field.key,
            Self::File(field) => &field.key,
            Self::Hidden(field) => &field.key,
            Self::Computed(field) => &field.key,
            Self::Dynamic(field) => &field.key,
            Self::Notice(field) => &field.key,
        }
    }

    /// Shared visibility accessor.
    pub fn visible(&self) -> &VisibilityMode {
        match self {
            Self::String(field) => &field.visible,
            Self::Secret(field) => &field.visible,
            Self::Number(field) => &field.visible,
            Self::Boolean(field) => &field.visible,
            Self::Select(field) => &field.visible,
            Self::Object(field) => &field.visible,
            Self::List(field) => &field.visible,
            Self::Mode(field) => &field.visible,
            Self::Code(field) => &field.visible,
            Self::Date(field) => &field.visible,
            Self::DateTime(field) => &field.visible,
            Self::Time(field) => &field.visible,
            Self::Color(field) => &field.visible,
            Self::File(field) => &field.visible,
            Self::Hidden(field) => &field.visible,
            Self::Computed(field) => &field.visible,
            Self::Dynamic(field) => &field.visible,
            Self::Notice(field) => &field.visible,
        }
    }

    /// Shared required accessor.
    pub fn required(&self) -> &RequiredMode {
        match self {
            Self::String(field) => &field.required,
            Self::Secret(field) => &field.required,
            Self::Number(field) => &field.required,
            Self::Boolean(field) => &field.required,
            Self::Select(field) => &field.required,
            Self::Object(field) => &field.required,
            Self::List(field) => &field.required,
            Self::Mode(field) => &field.required,
            Self::Code(field) => &field.required,
            Self::Date(field) => &field.required,
            Self::DateTime(field) => &field.required,
            Self::Time(field) => &field.required,
            Self::Color(field) => &field.required,
            Self::File(field) => &field.required,
            Self::Hidden(field) => &field.required,
            Self::Computed(field) => &field.required,
            Self::Dynamic(field) => &field.required,
            Self::Notice(field) => &field.required,
        }
    }

    /// Shared rules accessor.
    pub fn rules(&self) -> &[Rule] {
        match self {
            Self::String(field) => field.rules.as_slice(),
            Self::Secret(field) => field.rules.as_slice(),
            Self::Number(field) => field.rules.as_slice(),
            Self::Boolean(field) => field.rules.as_slice(),
            Self::Select(field) => field.rules.as_slice(),
            Self::Object(field) => field.rules.as_slice(),
            Self::List(field) => field.rules.as_slice(),
            Self::Mode(field) => field.rules.as_slice(),
            Self::Code(field) => field.rules.as_slice(),
            Self::Date(field) => field.rules.as_slice(),
            Self::DateTime(field) => field.rules.as_slice(),
            Self::Time(field) => field.rules.as_slice(),
            Self::Color(field) => field.rules.as_slice(),
            Self::File(field) => field.rules.as_slice(),
            Self::Hidden(field) => field.rules.as_slice(),
            Self::Computed(field) => field.rules.as_slice(),
            Self::Dynamic(field) => field.rules.as_slice(),
            Self::Notice(field) => field.rules.as_slice(),
        }
    }

    /// Shared default-value accessor.
    pub fn default(&self) -> Option<&Value> {
        match self {
            Self::String(field) => field.default.as_ref(),
            Self::Secret(field) => field.default.as_ref(),
            Self::Number(field) => field.default.as_ref(),
            Self::Boolean(field) => field.default.as_ref(),
            Self::Select(field) => field.default.as_ref(),
            Self::Object(field) => field.default.as_ref(),
            Self::List(field) => field.default.as_ref(),
            Self::Mode(field) => field.default.as_ref(),
            Self::Code(field) => field.default.as_ref(),
            Self::Date(field) => field.default.as_ref(),
            Self::DateTime(field) => field.default.as_ref(),
            Self::Time(field) => field.default.as_ref(),
            Self::Color(field) => field.default.as_ref(),
            Self::File(field) => field.default.as_ref(),
            Self::Hidden(field) => field.default.as_ref(),
            Self::Computed(field) => field.default.as_ref(),
            Self::Dynamic(field) => field.default.as_ref(),
            Self::Notice(field) => field.default.as_ref(),
        }
    }
}

impl From<StringField> for Field {
    fn from(value: StringField) -> Self {
        Self::String(value)
    }
}

impl From<SecretField> for Field {
    fn from(value: SecretField) -> Self {
        Self::Secret(value)
    }
}

impl From<NumberField> for Field {
    fn from(value: NumberField) -> Self {
        Self::Number(value)
    }
}

impl From<BooleanField> for Field {
    fn from(value: BooleanField) -> Self {
        Self::Boolean(value)
    }
}

impl From<SelectField> for Field {
    fn from(value: SelectField) -> Self {
        Self::Select(value)
    }
}

impl From<ObjectField> for Field {
    fn from(value: ObjectField) -> Self {
        Self::Object(value)
    }
}

impl From<ListField> for Field {
    fn from(value: ListField) -> Self {
        Self::List(value)
    }
}

impl From<ModeField> for Field {
    fn from(value: ModeField) -> Self {
        Self::Mode(value)
    }
}

impl From<CodeField> for Field {
    fn from(value: CodeField) -> Self {
        Self::Code(value)
    }
}

impl From<DateField> for Field {
    fn from(value: DateField) -> Self {
        Self::Date(value)
    }
}

impl From<DateTimeField> for Field {
    fn from(value: DateTimeField) -> Self {
        Self::DateTime(value)
    }
}

impl From<TimeField> for Field {
    fn from(value: TimeField) -> Self {
        Self::Time(value)
    }
}

impl From<ColorField> for Field {
    fn from(value: ColorField) -> Self {
        Self::Color(value)
    }
}

impl From<FileField> for Field {
    fn from(value: FileField) -> Self {
        Self::File(value)
    }
}

impl From<HiddenField> for Field {
    fn from(value: HiddenField) -> Self {
        Self::Hidden(value)
    }
}

impl From<ComputedField> for Field {
    fn from(value: ComputedField) -> Self {
        Self::Computed(value)
    }
}

impl From<DynamicField> for Field {
    fn from(value: DynamicField) -> Self {
        Self::Dynamic(value)
    }
}

impl From<NoticeField> for Field {
    fn from(value: NoticeField) -> Self {
        Self::Notice(value)
    }
}
