//! Task queue interface and in-memory implementation.
//!
//! Used to distribute work to workers; at-least-once delivery with ack/nack.

use std::{
    collections::HashMap,
    future::Future,
    sync::{
        Arc,
        atomic::{AtomicUsize, Ordering},
    },
    time::Duration,
};

use async_channel::{Receiver, Sender};
use thiserror::Error;
use tokio::{sync::Mutex, time::Instant};

/// Errors returned by queue operations.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum QueueError {
    /// Task not found (e.g. ack/nack unknown id).
    #[error("{entity} not found: {id}")]
    NotFound {
        /// Entity type (for example, `task`).
        entity: String,
        /// Missing entity identifier.
        id: String,
    },

    /// Internal queue failure (full, closed, etc.).
    #[error("internal error: {0}")]
    Internal(String),
}

impl QueueError {
    /// Convenience constructor for [`QueueError::NotFound`].
    pub fn not_found(entity: impl Into<String>, id: impl Into<String>) -> Self {
        Self::NotFound {
            entity: entity.into(),
            id: id.into(),
        }
    }
}

/// Work queue interface for distributing tasks to workers.
///
/// At-least-once semantics: enqueue → dequeue → ack (or nack to requeue).
///
/// Methods are desugared from `async fn` to `fn -> impl Future + Send` to
/// avoid a `Pin<Box<dyn Future>>` wrapper and preserve `Send` on the returned
/// futures . Callers that use
/// `tokio::spawn` may still need an owning `async move { ... }` wrapper and
/// owned/cloned inputs to satisfy the spawned future's `'static` requirement.
pub trait TaskQueue: Send + Sync {
    /// Enqueue a task. Returns a task ID.
    fn enqueue(
        &self,
        payload: serde_json::Value,
    ) -> impl Future<Output = Result<String, QueueError>> + Send;

    /// Dequeue the next available task.
    ///
    /// Distinguishes timeout from a closed queue so callers can react
    /// differently to "no work yet" vs "producer is gone".
    fn dequeue(
        &self,
        timeout: Duration,
    ) -> impl Future<Output = Result<DequeueResult, QueueError>> + Send;

    /// Acknowledge successful processing.
    fn ack(&self, task_id: &str) -> impl Future<Output = Result<(), QueueError>> + Send;

    /// Negative-acknowledge — requeue for retry.
    ///
    /// **Backpressure asymmetry:** unlike `enqueue`, which fails fast when the queue
    /// is full, `nack` waits for capacity — dropping a task that already failed
    /// once would break at-least-once delivery. A caller that nacks in a tight loop
    /// on transient failures while producers keep the queue full can therefore be
    /// starved (the deadlock anti-pattern of a consumer blocking on the channel it
    /// drains). Bound the wait at the call site, or route the task elsewhere, if
    /// the executor may nack under sustained load.
    fn nack(&self, task_id: &str) -> impl Future<Output = Result<(), QueueError>> + Send;

    /// Total number of tasks tracked by the queue: queued + in-flight.
    ///
    /// This is a workload cardinality view, not just channel depth.
    fn len(&self) -> impl Future<Output = Result<usize, QueueError>> + Send;

    /// Number of tasks currently waiting in the queue channel.
    fn queued_len(&self) -> impl Future<Output = Result<usize, QueueError>> + Send;

    /// Number of tasks currently leased to workers and awaiting ack/nack.
    fn in_flight_len(&self) -> impl Future<Output = Result<usize, QueueError>> + Send;

    /// Whether the queue is empty.
    fn is_empty(&self) -> impl Future<Output = Result<bool, QueueError>> + Send {
        async { Ok(self.len().await? == 0) }
    }
}

/// Outcome of a dequeue attempt.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum DequeueResult {
    /// A task was successfully leased to a worker.
    Item {
        /// Task ID generated by enqueue.
        task_id: String,
        /// Opaque payload for worker execution.
        payload: serde_json::Value,
    },
    /// No item arrived before the timeout elapsed.
    Timeout,
    /// Queue is closed and cannot deliver more items.
    Closed,
}

#[derive(Debug, Clone)]
struct QueueItem {
    id: String,
    payload: serde_json::Value,
}

#[derive(Debug, Clone)]
struct InFlightEntry {
    item: QueueItem,
    lease_deadline: Instant,
}

/// In-memory bounded task queue.
///
/// Tasks: Queued → In-flight (dequeued) → Done (acked) or requeued (nacked).
///
/// The receiver is multi-consumer (`async_channel`), so multiple concurrent
/// `dequeue` callers may park inside `recv()` simultaneously. A previous
/// `Arc<Mutex<mpsc::Receiver>>` design forced workers to serialize on the
/// mutex, capping effective parallelism at 1 (issue #279).
pub struct MemoryQueue {
    sender: Sender<QueueItem>,
    receiver: Receiver<QueueItem>,
    in_flight: Arc<Mutex<HashMap<String, InFlightEntry>>>,
    queued_count: AtomicUsize,
    visibility_timeout: Duration,
}

impl MemoryQueue {
    const DEFAULT_VISIBILITY_TIMEOUT: Duration = Duration::from_secs(30);

    /// Create a new memory queue with the given capacity.
    #[must_use]
    pub fn new(capacity: usize) -> Self {
        Self::new_with_visibility_timeout(capacity, Self::DEFAULT_VISIBILITY_TIMEOUT)
    }

    /// Create a new memory queue with an explicit visibility timeout.
    ///
    /// A dequeued task must be acknowledged within this timeout; otherwise it
    /// is considered stale and can be redelivered by a later [`TaskQueue::dequeue`].
    #[must_use]
    pub fn new_with_visibility_timeout(capacity: usize, visibility_timeout: Duration) -> Self {
        let (sender, receiver) = async_channel::bounded(capacity);
        Self {
            sender,
            receiver,
            in_flight: Arc::new(Mutex::new(HashMap::new())),
            queued_count: AtomicUsize::new(0),
            visibility_timeout,
        }
    }

    async fn try_reclaim_stale_in_flight(&self) -> Option<QueueItem> {
        let now = Instant::now();
        let mut in_flight = self.in_flight.lock().await;
        let stale_task_id = in_flight
            .iter()
            .find(|(_, entry)| entry.lease_deadline <= now)
            .map(|(task_id, _)| task_id.clone())?;
        in_flight.remove(&stale_task_id).map(|entry| entry.item)
    }

    async fn lease_item(&self, item: QueueItem) -> (String, serde_json::Value) {
        let id = item.id.clone();
        let payload = item.payload.clone();
        let lease_deadline = Instant::now() + self.visibility_timeout;
        self.in_flight.lock().await.insert(
            id.clone(),
            InFlightEntry {
                item,
                lease_deadline,
            },
        );
        (id, payload)
    }
}

impl TaskQueue for MemoryQueue {
    async fn enqueue(&self, payload: serde_json::Value) -> Result<String, QueueError> {
        let id = uuid::Uuid::new_v4().to_string();
        let item = QueueItem {
            id: id.clone(),
            payload,
        };
        self.sender
            .try_send(item)
            .map_err(|e| QueueError::Internal(format!("queue full or closed: {e}")))?;
        self.queued_count.fetch_add(1, Ordering::Relaxed);
        Ok(id)
    }

    async fn dequeue(&self, timeout: Duration) -> Result<DequeueResult, QueueError> {
        if let Some(item) = self.try_reclaim_stale_in_flight().await {
            let (task_id, payload) = self.lease_item(item).await;
            return Ok(DequeueResult::Item { task_id, payload });
        }

        // No mutex around `recv()` — `async_channel::Receiver` is multi-consumer
        // and `recv()` takes `&self`, so concurrent workers register independent
        // wakers and park in parallel.
        let result = tokio::time::timeout(timeout, self.receiver.recv()).await;
        match result {
            Ok(Ok(item)) => {
                self.queued_count.fetch_sub(1, Ordering::Relaxed);
                let (task_id, payload) = self.lease_item(item).await;
                Ok(DequeueResult::Item { task_id, payload })
            },
            Ok(Err(_)) => Ok(DequeueResult::Closed),
            Err(_) => Ok(DequeueResult::Timeout),
        }
    }

    async fn ack(&self, task_id: &str) -> Result<(), QueueError> {
        let removed = self.in_flight.lock().await.remove(task_id);
        if removed.is_none() {
            return Err(QueueError::not_found("Task", task_id));
        }
        Ok(())
    }

    /// Requeue a leased task, waiting for capacity if the queue is full.
    ///
    /// The task stays in flight until the requeue succeeds, so a saturated queue
    /// never loses it (at-least-once). The wait is unbounded by design; a warning
    /// is logged once when it exceeds half the visibility timeout, so starvation is
    /// visible before the lease itself would expire.
    async fn nack(&self, task_id: &str) -> Result<(), QueueError> {
        // Keep the item in-flight until requeue succeeds to preserve
        // at-least-once guarantees when the queue is saturated.
        let item = {
            let in_flight = self.in_flight.lock().await;
            in_flight.get(task_id).map(|entry| entry.item.clone())
        };
        let Some(item) = item else {
            return Err(QueueError::not_found("Task", task_id));
        };

        let send = self.sender.send(item);
        tokio::pin!(send);
        let warn_after = self.visibility_timeout / 2;
        let sent = if let Ok(result) = tokio::time::timeout(warn_after, &mut send).await {
            result
        } else {
            tracing::warn!(
                task_id,
                waited_ms = u64::try_from(warn_after.as_millis()).unwrap_or(u64::MAX),
                "queue: nack is still waiting for capacity; the queue is saturated"
            );
            send.await
        };
        sent.map_err(|e| QueueError::Internal(format!("requeue failed: {e}")))?;
        self.queued_count.fetch_add(1, Ordering::Relaxed);
        let _ = self.in_flight.lock().await.remove(task_id);
        Ok(())
    }

    async fn len(&self) -> Result<usize, QueueError> {
        Ok(self.queued_count() + self.in_flight_count().await)
    }

    async fn queued_len(&self) -> Result<usize, QueueError> {
        Ok(self.queued_count())
    }

    async fn in_flight_len(&self) -> Result<usize, QueueError> {
        Ok(self.in_flight_count().await)
    }
}

impl MemoryQueue {
    fn queued_count(&self) -> usize {
        self.queued_count.load(Ordering::Relaxed)
    }

    async fn in_flight_count(&self) -> usize {
        self.in_flight.lock().await.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn dequeue_reports_timeout_distinct_from_closed() {
        let queue = MemoryQueue::new(1);
        let got = queue.dequeue(Duration::from_millis(10)).await.unwrap();
        assert_eq!(got, DequeueResult::Timeout);
    }

    #[tokio::test]
    async fn len_includes_in_flight_work() {
        let queue = MemoryQueue::new(2);
        let id = queue
            .enqueue(serde_json::json!({"task":"x"}))
            .await
            .unwrap();
        assert_eq!(queue.len().await.unwrap(), 1);
        assert_eq!(queue.queued_len().await.unwrap(), 1);
        assert_eq!(queue.in_flight_len().await.unwrap(), 0);

        let got = queue.dequeue(Duration::from_millis(50)).await.unwrap();
        assert!(matches!(
            got,
            DequeueResult::Item { task_id, .. } if task_id == id
        ));
        // Still one unit of work, but now leased.
        assert_eq!(queue.len().await.unwrap(), 1);
        assert_eq!(queue.queued_len().await.unwrap(), 0);
        assert_eq!(queue.in_flight_len().await.unwrap(), 1);
    }

    #[tokio::test]
    async fn nack_waits_for_capacity_and_preserves_task() {
        let queue = Arc::new(MemoryQueue::new(1));

        let first_id = queue
            .enqueue(serde_json::json!({"task":"first"}))
            .await
            .unwrap();
        let (dequeued_id, _) = match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
            DequeueResult::Item { task_id, payload } => (task_id, payload),
            other => panic!("expected dequeued task, got {other:?}"),
        };
        assert_eq!(dequeued_id, first_id);

        // Fill the queue so nack must wait for capacity.
        queue
            .enqueue(serde_json::json!({"task":"filler"}))
            .await
            .unwrap();

        let queue_for_nack = Arc::clone(&queue);
        let id_for_nack = dequeued_id.clone();
        let nack_task = tokio::spawn(async move { queue_for_nack.nack(&id_for_nack).await });

        tokio::time::sleep(Duration::from_millis(20)).await;
        assert!(
            !nack_task.is_finished(),
            "nack should block while queue is full"
        );

        // Free one slot, then nack should complete and requeue original task.
        let (_filler_id, _filler_payload) =
            match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
                DequeueResult::Item { task_id, payload } => (task_id, payload),
                other => panic!("expected filler dequeue, got {other:?}"),
            };
        nack_task.await.unwrap().unwrap();

        let (requeued_id, _) = match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
            DequeueResult::Item { task_id, payload } => (task_id, payload),
            other => panic!("expected requeued task, got {other:?}"),
        };
        assert_eq!(requeued_id, dequeued_id);
    }

    /// Counts WARN events so the saturation warning can be asserted.
    struct WarnCounter(Arc<AtomicUsize>);

    impl<S: tracing::Subscriber> tracing_subscriber::Layer<S> for WarnCounter {
        fn on_event(
            &self,
            event: &tracing::Event<'_>,
            _ctx: tracing_subscriber::layer::Context<'_, S>,
        ) {
            if *event.metadata().level() == tracing::Level::WARN {
                self.0.fetch_add(1, Ordering::SeqCst);
            }
        }
    }

    #[tokio::test]
    async fn nack_warns_once_when_capacity_wait_exceeds_half_the_visibility_timeout() {
        use tracing_subscriber::layer::SubscriberExt;

        let warnings = Arc::new(AtomicUsize::new(0));
        let subscriber = tracing_subscriber::registry().with(WarnCounter(Arc::clone(&warnings)));
        let _guard = tracing::subscriber::set_default(subscriber);

        let queue = Arc::new(MemoryQueue::new_with_visibility_timeout(
            1,
            Duration::from_millis(400),
        ));
        queue
            .enqueue(serde_json::json!({"task":"a"}))
            .await
            .unwrap();
        let DequeueResult::Item { task_id, .. } =
            queue.dequeue(Duration::from_millis(50)).await.unwrap()
        else {
            panic!("expected a dequeued task");
        };
        queue
            .enqueue(serde_json::json!({"task":"filler"}))
            .await
            .unwrap();

        let queue_for_nack = Arc::clone(&queue);
        let id_for_nack = task_id.clone();
        let nack_task = tokio::spawn(async move { queue_for_nack.nack(&id_for_nack).await });

        // Past half the visibility timeout (200ms) but inside the lease (400ms): the
        // warning has fired, the nack is still waiting, and nothing was dropped.
        // Staying inside the lease matters: once it expires, `dequeue` re-leases the
        // stale in-flight task ahead of the channel, so the filler would never be
        // consumed and the pending nack would never get its slot.
        tokio::time::sleep(Duration::from_millis(260)).await;
        assert!(!nack_task.is_finished(), "nack keeps waiting after warning");
        assert_eq!(warnings.load(Ordering::SeqCst), 1);

        // Free a slot: the same pending send completes and requeues the task.
        let DequeueResult::Item { .. } = queue.dequeue(Duration::from_millis(50)).await.unwrap()
        else {
            panic!("expected the filler");
        };
        nack_task.await.unwrap().unwrap();
        assert_eq!(warnings.load(Ordering::SeqCst), 1, "warned exactly once");
        let DequeueResult::Item {
            task_id: requeued, ..
        } = queue.dequeue(Duration::from_millis(50)).await.unwrap()
        else {
            panic!("expected the requeued task");
        };
        assert_eq!(requeued, task_id);
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn dequeue_supports_concurrent_consumers() {
        // Regression for issue #279 — the previous `Arc<Mutex<Receiver>>`
        // design serialized all workers onto one in-flight `recv()` at a
        // time. With a multi-consumer channel, N workers can each park in
        // `recv()` independently and drain a saturated queue concurrently.
        const ITEMS: usize = 64;
        const WORKERS: usize = 8;

        let queue = Arc::new(MemoryQueue::new(ITEMS));
        for i in 0..ITEMS {
            queue.enqueue(serde_json::json!({ "i": i })).await.unwrap();
        }

        async fn drain(queue: Arc<MemoryQueue>, processed: Arc<AtomicUsize>) {
            while let DequeueResult::Item { task_id, .. } =
                queue.dequeue(Duration::from_millis(50)).await.unwrap()
            {
                queue.ack(&task_id).await.unwrap();
                processed.fetch_add(1, Ordering::Relaxed);
            }
        }

        let processed = Arc::new(AtomicUsize::new(0));
        let mut handles = Vec::with_capacity(WORKERS);
        for _ in 0..WORKERS {
            handles.push(tokio::spawn(drain(
                Arc::clone(&queue),
                Arc::clone(&processed),
            )));
        }

        for h in handles {
            h.await.unwrap();
        }

        assert_eq!(processed.load(Ordering::Relaxed), ITEMS);
        assert_eq!(queue.queued_len().await.unwrap(), 0);
        assert_eq!(queue.in_flight_len().await.unwrap(), 0);
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn dequeue_does_not_block_other_workers_during_long_timeout() {
        // Regression for issue #279 — with the receiver mutex held across
        // `tokio::time::timeout(timeout, rx.recv())`, a worker stuck in a
        // long timeout would prevent any other worker from observing newly
        // enqueued items. We start two workers with a long timeout, enqueue
        // two items 50 ms apart, and assert both workers complete well
        // within the timeout window.
        let queue = Arc::new(MemoryQueue::new(2));
        let long_timeout = Duration::from_secs(5);

        let q1 = Arc::clone(&queue);
        let h1 = tokio::spawn(async move { q1.dequeue(long_timeout).await });
        let q2 = Arc::clone(&queue);
        let h2 = tokio::spawn(async move { q2.dequeue(long_timeout).await });

        // Give both workers a moment to register their wakers in `recv()`.
        tokio::time::sleep(Duration::from_millis(20)).await;

        queue.enqueue(serde_json::json!({"i": 1})).await.unwrap();
        tokio::time::sleep(Duration::from_millis(50)).await;
        queue.enqueue(serde_json::json!({"i": 2})).await.unwrap();

        let start = std::time::Instant::now();
        let r1 = h1.await.unwrap().unwrap();
        let r2 = h2.await.unwrap().unwrap();
        let elapsed = start.elapsed();

        assert!(matches!(r1, DequeueResult::Item { .. }));
        assert!(matches!(r2, DequeueResult::Item { .. }));
        assert!(
            elapsed < Duration::from_secs(1),
            "both dequeues should resolve well before the {long_timeout:?} timeout, got {elapsed:?}"
        );
    }

    #[tokio::test]
    async fn stale_in_flight_task_is_redelivered() {
        let queue = MemoryQueue::new_with_visibility_timeout(1, Duration::from_millis(20));
        let id = queue
            .enqueue(serde_json::json!({"task":"stale"}))
            .await
            .unwrap();
        let (first_delivery, _) = match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
            DequeueResult::Item { task_id, payload } => (task_id, payload),
            other => panic!("expected first delivery, got {other:?}"),
        };
        assert_eq!(first_delivery, id);

        tokio::time::sleep(Duration::from_millis(30)).await;

        let (second_delivery, _) = match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
            DequeueResult::Item { task_id, payload } => (task_id, payload),
            other => panic!("expected stale redelivery, got {other:?}"),
        };
        assert_eq!(second_delivery, id);
    }
}
