//! Typed pending state for interactive credential flows (v2).
//!
//! [`PendingState`] represents ephemeral data held between the initial
//! `resolve()` call and the subsequent `continue_resolve()` callback.
//! The framework stores it encrypted with TTL and single-use semantics
//! via `PendingStateStore` -- credential authors never manage storage
//! directly.
//!
//! Non-interactive credentials use [`NoPendingState`] as a zero-cost
//! marker type.
//!
//! [`PendingToken`] is the opaque handle returned by the store on `put()`.

use std::time::Duration;

use serde::{Deserialize, Serialize, de::DeserializeOwned};
use zeroize::Zeroize;

/// Typed pending state for interactive credential flows.
///
/// Stored via `PendingStateStore` with encryption, TTL, single-use.
///
/// # Security properties
///
/// - **TTL enforced:** [`expires_in`](PendingState::expires_in) determines max lifetime (typically
///   5-15 min).
/// - **Single-use:** consumed (deleted) on first read by `continue_resolve()`.
/// - **Encrypted at rest** by the `PendingStateStore` implementation.
/// - **Zeroize on drop:** secrets zeroed when state is dropped.
/// - Serialization buffers wrapped in `Zeroizing<Vec<u8>>` by store implementation.
pub trait PendingState: Serialize + DeserializeOwned + Send + Sync + Zeroize + 'static {
    /// Stable identifier for this pending-state type
    /// (e.g. `"oauth2_pending"`).
    const KIND: &'static str;

    /// How long this pending state should remain valid.
    fn expires_in(&self) -> Duration;
}

/// Marker type for non-interactive credentials.
///
/// Credential types that resolve in a single step (API key, basic auth,
/// database) use `NoPendingState` as their `Credential::Pending`
/// associated type. It serializes to `null` and expires immediately.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NoPendingState;

impl Zeroize for NoPendingState {
    fn zeroize(&mut self) {
        // No sensitive data to zeroize.
    }
}

impl PendingState for NoPendingState {
    const KIND: &'static str = "none";

    fn expires_in(&self) -> Duration {
        Duration::ZERO
    }
}

// ── PendingToken ───────────────────────────────────────────────────────

/// Opaque handle to a stored [`PendingState`].
///
/// Generated by [`PendingStateStore::put()`](crate::pending_store::PendingStateStore::put),
/// consumed by [`PendingStateStore::consume()`](crate::pending_store::PendingStateStore::consume).
///
/// Contains a 32-byte CSPRNG value encoded as URL-safe base64 (no padding).
/// The token is bound to (credential_kind, owner_id, session_id) at storage
/// time — all four dimensions are validated on consume.
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PendingToken(String);

// Manual `Debug` so that `tracing::debug!(?token)` — which is exactly the
// path a bearer-token value would most plausibly leak through — prints the
// same redacted placeholder as `Display`. A derived `Debug` would print the
// base64 CSPRNG contents verbatim.
impl std::fmt::Debug for PendingToken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("PendingToken([REDACTED])")
    }
}

impl PendingToken {
    /// Generates a new cryptographically random token.
    ///
    /// Callable by pending-store impls that live outside this crate (see
    /// `nebula_storage::credential::pending::InMemoryPendingStore` —
    /// canonical home per ADR-0032 §7).
    pub fn generate() -> Self {
        use rand::RngExt;
        let mut rng = rand::rng();
        let bytes: [u8; 32] = rng.random();
        Self(base64::Engine::encode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            bytes,
        ))
    }

    /// Returns the token as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for PendingToken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "PendingToken([REDACTED])")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_produces_unique_tokens() {
        let t1 = PendingToken::generate();
        let t2 = PendingToken::generate();
        assert_ne!(t1, t2);
    }

    #[test]
    fn as_str_returns_base64() {
        let token = PendingToken::generate();
        assert_eq!(token.as_str().len(), 43);
    }

    #[test]
    fn display_is_redacted() {
        let token = PendingToken::generate();
        let display = format!("{token}");
        assert!(display.contains("REDACTED"));
        assert!(!display.contains(token.as_str()));
    }

    #[test]
    fn serialize_deserialize_roundtrip() {
        let token = PendingToken::generate();
        let json = serde_json::to_string(&token).unwrap();
        let back: PendingToken = serde_json::from_str(&json).unwrap();
        assert_eq!(token, back);
    }
}
