//! Parameter schema system for Nebula workflow nodes.
//!
//! ## Quick Start
//!
//! ```
//! use nebula_parameter::prelude::*;
//!
//! let params = ParameterCollection::new()
//!     .add(
//!         Parameter::string("api_key")
//!             .label("API Key")
//!             .required()
//!             .secret(),
//!     )
//!     .add(Parameter::integer("timeout_ms").label("Timeout (ms)"));
//!
//! assert_eq!(params.len(), 2);
//! ```
//!
//! ## Core Types
//!
//! - [`Parameter`] — Single parameter definition with fluent builder
//! - [`ParameterType`] — Type-specific configuration (19 variants)
//! - [`ParameterCollection`] — Ordered collection of parameters
//! - [`ParameterValues`] — Runtime key-value map with typed accessors
//! - [`Condition`] — Declarative predicates for field visibility/required logic

#![forbid(unsafe_code)]
#![warn(missing_docs)]

// ── Public modules ──────────────────────────────────────────────────────────
/// Typed closure builder for parameter collections.
pub mod builder;
/// Parameter collection container.
pub mod collection;
/// Declarative conditions for field visibility and required logic.
pub mod conditions;
/// Object display mode.
pub mod display_mode;
/// Error types for parameter operations.
pub mod error;
/// Typed field definitions for the Filter condition builder.
pub mod filter_field;
/// Input hints for String parameter UI rendering.
pub mod input_hint;
/// Schema lint diagnostics.
pub mod lint;
/// Inline loader types for select, dynamic, and filter fields.
pub mod loader;
/// Paginated loader result.
pub mod loader_result;
/// Default and mode normalization helpers.
pub mod normalize;
/// Notice severity levels.
pub mod notice;
/// Option models for select parameters.
pub mod option;
/// Parameter definition with fluent builder.
pub mod parameter;
/// Type-specific parameter configuration.
pub mod parameter_type;
/// Typed parameter path references.
pub mod path;
/// Validation profile selection.
pub mod profile;
/// Validation output report.
pub mod report;
/// Declarative validation rules.
pub mod rules;
/// Runtime wrappers around validated parameter values.
pub mod runtime;
/// Supporting spec types.
pub mod spec;
/// Declarative value transformers.
pub mod transformer;
/// Static validation engine.
pub mod validate;
/// Runtime parameter value container and typed accessors.
pub mod values;

// ── Top-level re-exports ────────────────────────────────────────────────────
pub use nebula_parameter_macros::{EnumSelect, Parameters};

/// Trait generated by `#[derive(Parameters)]`.
///
/// Returns the parameter schema for a struct.
pub trait HasParameters {
    /// Returns the parameter collection describing all fields.
    fn parameters() -> ParameterCollection;
}

/// Trait generated by `#[derive(EnumSelect)]`.
///
/// Returns select options derived from enum variants.
pub trait HasSelectOptions {
    /// Returns select options for all variants.
    fn select_options() -> Vec<SelectOption>;
}

/// Trait for mapping a Rust type to a Parameter at macro expansion time.
///
/// Implemented by `#[derive(EnumSelect)]` for enums. For structs with
/// `HasParameters`, a blanket impl generates an Object parameter.
pub trait InferParameterType {
    /// Create a Parameter definition for this type.
    fn into_parameter(id: &str) -> Parameter;
}

pub use builder::{
    BooleanBuilder, CodeBuilder, GroupBuilder, ListBuilder, NumberBuilder, ObjectBuilder,
    ParameterCollectionBuilder, SelectBuilder, StringBuilder,
};
pub use collection::ParameterCollection;
pub use conditions::Condition;
pub use display_mode::{ComputedReturn, DisplayMode};
pub use error::ParameterError;
pub use filter_field::{FilterField, FilterFieldType};
pub use input_hint::InputHint;
pub use lint::{LintDiagnostic, LintLevel, lint_collection};
pub use loader::{FilterFieldLoader, LoaderContext, LoaderError, OptionLoader, RecordLoader};
pub use loader_result::LoaderResult;
pub use notice::NoticeSeverity;
pub use option::SelectOption;
pub use parameter::Parameter;
pub use parameter_type::ParameterType;
pub use path::ParameterPath;
pub use profile::ValidationProfile;
pub use report::ValidationReport;
pub use rules::Rule;
pub use runtime::ValidatedValues;
pub use spec::{
    FieldSpec, FieldSpecConvertError, FilterCombinator, FilterExpr, FilterGroup, FilterOp,
    FilterRule,
};
pub use transformer::Transformer;
pub use values::{ModeValueRef, ParameterValue, ParameterValues};

/// Common imports for working with parameters.
pub mod prelude {
    pub use crate::{
        EnumSelect, HasParameters, HasSelectOptions, InferParameterType, Parameters,
        collection::ParameterCollection,
        conditions::Condition,
        display_mode::{ComputedReturn, DisplayMode},
        error::ParameterError,
        filter_field::{FilterField, FilterFieldType},
        input_hint::InputHint,
        lint::{LintDiagnostic, LintLevel, lint_collection},
        loader::{FilterFieldLoader, LoaderContext, LoaderError, OptionLoader, RecordLoader},
        loader_result::LoaderResult,
        notice::NoticeSeverity,
        option::SelectOption,
        parameter::Parameter,
        parameter_type::ParameterType,
        path::ParameterPath,
        profile::ValidationProfile,
        report::ValidationReport,
        rules::Rule,
        runtime::ValidatedValues,
        spec::{
            FieldSpec, FieldSpecConvertError, FilterCombinator, FilterExpr, FilterGroup, FilterOp,
            FilterRule,
        },
        transformer::Transformer,
        values::{ModeValueRef, ParameterValue, ParameterValues},
    };
}
