//! Opaque token handle for pending interactive credential flows.

use serde::{Deserialize, Serialize};

/// Opaque handle to a stored [`PendingState`](crate::pending::PendingState).
///
/// Generated by [`PendingStateStore::put()`](crate::pending_store::PendingStateStore::put),
/// consumed by [`PendingStateStore::consume()`](crate::pending_store::PendingStateStore::consume).
///
/// Contains a 32-byte CSPRNG value encoded as URL-safe base64 (no padding).
/// The token is bound to (credential_kind, owner_id, session_id) at storage
/// time — all four dimensions are validated on consume.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PendingToken(String);

impl PendingToken {
    /// Generates a new cryptographically random token.
    // Reason: no in-crate caller yet — `InMemoryPendingStore` will use this.
    #[allow(dead_code)]
    pub(crate) fn generate() -> Self {
        use rand::RngExt;
        let mut rng = rand::rng();
        let bytes: [u8; 32] = rng.random();
        Self(base64::Engine::encode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            bytes,
        ))
    }

    /// Returns the token as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for PendingToken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Redact in Display to prevent accidental logging
        write!(f, "PendingToken([REDACTED])")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_produces_unique_tokens() {
        let t1 = PendingToken::generate();
        let t2 = PendingToken::generate();
        assert_ne!(t1, t2);
    }

    #[test]
    fn as_str_returns_base64() {
        let token = PendingToken::generate();
        // 32 bytes → 43 chars in URL-safe base64 no-pad
        assert_eq!(token.as_str().len(), 43);
    }

    #[test]
    fn display_is_redacted() {
        let token = PendingToken::generate();
        let display = format!("{token}");
        assert!(display.contains("REDACTED"));
        assert!(!display.contains(token.as_str()));
    }

    #[test]
    fn serialize_deserialize_roundtrip() {
        let token = PendingToken::generate();
        let json = serde_json::to_string(&token).unwrap();
        let back: PendingToken = serde_json::from_str(&json).unwrap();
        assert_eq!(token, back);
    }
}
