// Auto-generated by tauri-specta — do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getApiProfile() : Promise<string> {
    return await TAURI_INVOKE("get_api_profile");
},
async closeSplashscreen() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_splashscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAuthState() : Promise<AuthState> {
    return await TAURI_INVOKE("get_auth_state");
},
async authLogin(provider: string) : Promise<Result<AuthState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_login", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authLogout() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authGetUser(provider: string) : Promise<Result<UserProfile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_user", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRefreshToken(provider: string) : Promise<Result<AuthState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_refresh_token", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConnection() : Promise<ConnectionConfig> {
    return await TAURI_INVOKE("get_connection");
},
async setConnection(config: ConnectionConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_connection", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCredentials() : Promise<Credential[]> {
    return await TAURI_INVOKE("list_credentials");
},
async getCredential(id: string) : Promise<Result<Credential, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_credential", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCredential(request: CreateCredentialRequest) : Promise<Result<Credential, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_credential", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCredential(id: string, request: UpdateCredentialRequest) : Promise<Result<Credential, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_credential", { id, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCredential(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_credential", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rotateCredential(id: string) : Promise<Result<Credential, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rotate_credential", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkflows() : Promise<Workflow[]> {
    return await TAURI_INVOKE("list_workflows");
},
async getWorkflow(id: string) : Promise<Result<Workflow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkflow(request: CreateWorkflowRequest) : Promise<Result<Workflow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workflow", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWorkflow(id: string, request: UpdateWorkflowRequest) : Promise<Result<Workflow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_workflow", { id, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWorkflow(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_workflow", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPluginActions() : Promise<PluginAction[]> {
    return await TAURI_INVOKE("list_plugin_actions");
},
async saveWorkflowToFile(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_workflow_to_file", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadWorkflowFromFile() : Promise<Result<Workflow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workflow_from_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { Auth: string } | { Network: string } | { Keyring: string } | { Store: string } | { Window: string } | { Config: string }
export type AuthState = { status: AuthStatus; provider: string | null; accessToken: string; user: UserProfile | null; error: string | null }
export type AuthStatus = "signed_out" | "authorizing" | "signed_in"
export type ConnectionConfig = { mode: ConnectionMode; localBaseUrl: string; remoteBaseUrl: string }
export type ConnectionMode = "local" | "remote"
export type CreateCredentialRequest = { name: string; kind: string; state: string; tags: Partial<{ [key in string]: string }> | null }
export type CreateWorkflowRequest = { name: string; description: string | null; triggerMode: string; tags: Partial<{ [key in string]: string }> | null }
export type Credential = { id: string; name: string; kind: string; metadata: CredentialMetadata; state: string }
export type CredentialMetadata = { createdAt: string; lastAccessed: string | null; lastModified: string; version: number; expiresAt: string | null; ttlSeconds: number | null; tags: Partial<{ [key in string]: string }> }
export type NodeData = { actionType: string; label: string; parameters: string; inputs: NodePort[]; outputs: NodePort[]; icon: string | null; color: string | null; validationErrors: string[] | null }
export type NodePort = { id: string; name: string; type: string; dataType: string; required: boolean }
export type PluginAction = { key: string; name: string; description: string; version: number; group: string[]; icon: string | null; iconUrl: string | null; color: string | null; tags: string[] }
export type Position = { x: number; y: number }
export type UpdateCredentialRequest = { name: string | null; state: string; tags: Partial<{ [key in string]: string }> | null }
export type UpdateWorkflowRequest = { name: string | null; description: string | null; status: string | null; triggerMode: string | null; nodes: WorkflowNode[] | null; edges: WorkflowEdge[] | null; tags: Partial<{ [key in string]: string }> | null; serverUrl: string | null }
export type UserProfile = { id: string; login: string; name: string | null; email: string | null; avatarUrl: string | null }
export type Workflow = { id: string; name: string; status: string; triggerMode: string; nodes: WorkflowNode[]; edges: WorkflowEdge[]; metadata: WorkflowMetadata; serverUrl: string | null }
export type WorkflowEdge = { id: string; source: string; sourcePort: string; target: string; targetPort: string; label: string | null; animated: boolean | null; selected: boolean | null }
export type WorkflowMetadata = { createdAt: string; lastModified: string; lastDeployed: string | null; lastExecuted: string | null; version: number; tags: Partial<{ [key in string]: string }>; author: string | null; description: string | null }
export type WorkflowNode = { id: string; type: string; position: Position; data: NodeData; selected: boolean | null; dragging: boolean | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
