// Auto-generated by tauri-specta — do not edit manually.

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";

// Types

export type AuthStatus = "signed_out" | "authorizing" | "signed_in";

export type UserProfile = {
  id: string;
  login: string;
  name: string | null;
  email: string | null;
  avatarUrl: string | null;
};

export type AuthState = {
  status: AuthStatus;
  provider: string | null;
  accessToken: string;
  user: UserProfile | null;
  error: string | null;
};

export type ConnectionMode = "local" | "remote";

export type ConnectionConfig = {
  mode: ConnectionMode;
  localBaseUrl: string;
  remoteBaseUrl: string;
};

// Commands

export const commands = {
  async getApiProfile(): Promise<string> {
    return await TAURI_INVOKE<string>("get_api_profile");
  },

  async closeSplashscreen(): Promise<void> {
    await TAURI_INVOKE<void>("close_splashscreen");
  },

  async getAuthState(): Promise<AuthState> {
    return await TAURI_INVOKE<AuthState>("get_auth_state");
  },

  async authLogin(provider: string): Promise<AuthState> {
    return await TAURI_INVOKE<AuthState>("auth_login", { provider });
  },

  async authLogout(): Promise<void> {
    await TAURI_INVOKE<void>("auth_logout");
  },

  async authGetUser(provider: string): Promise<UserProfile> {
    return await TAURI_INVOKE<UserProfile>("auth_get_user", { provider });
  },

  async authRefreshToken(provider: string): Promise<AuthState> {
    return await TAURI_INVOKE<AuthState>("auth_refresh_token", { provider });
  },

  async getConnection(): Promise<ConnectionConfig> {
    return await TAURI_INVOKE<ConnectionConfig>("get_connection");
  },

  async setConnection(config: ConnectionConfig): Promise<void> {
    await TAURI_INVOKE<void>("set_connection", { config });
  },
};
