//! `TransactionalAction` DX trait demo — saga-style forward + compensation.
//!
//! Run:
//!
//! ```bash
//! cargo run -p nebula-examples --bin transactional
//! ```
//!
//! Demonstrates the Pending → Executed state machine generated by
//! `impl_transactional_action!`. `TestRuntime::run_stateful` drives one full
//! iteration (the forward operation); a real saga would re-invoke the same
//! action with the preserved state to run compensation — that second phase
//! is out of scope for a single-call example.

use nebula_sdk::prelude::*;

// ── Action definition ──────────────────────────────────────────────────────

struct TxDemoAction {
    meta: ActionMetadata,
}

impl TxDemoAction {
    fn new() -> Self {
        Self {
            meta: ActionMetadata::new(
                action_key!("tx_demo"),
                "Transactional Demo",
                "Fake charge + compensation via TransactionalAction DX trait",
            ),
        }
    }
}

impl ActionDependencies for TxDemoAction {}
impl Action for TxDemoAction {
    fn metadata(&self) -> &ActionMetadata {
        &self.meta
    }
}

impl TransactionalAction for TxDemoAction {
    type Input = Value;
    type Output = Value;
    type CompensationData = Value;

    async fn execute_tx(
        &self,
        input: Self::Input,
        _ctx: &impl ActionContext,
    ) -> Result<(Self::Output, Self::CompensationData), ActionError> {
        let amount = input
            .get("amount")
            .and_then(|v| v.as_u64())
            .ok_or_else(|| ActionError::validation("missing required field: amount"))?;
        if amount == 0 {
            return Err(ActionError::validation("amount must be > 0"));
        }
        let tx_id = format!("tx-{amount}");
        let output = json!({
            "tx_id": tx_id,
            "charged": amount,
            "status": "committed",
        });
        let comp = json!({
            "tx_id": tx_id,
            "refund_amount": amount,
        });
        Ok((output, comp))
    }

    async fn compensate(
        &self,
        data: Self::CompensationData,
        _ctx: &impl ActionContext,
    ) -> Result<(), ActionError> {
        eprintln!("[tx_demo] compensating: {data}");
        Ok(())
    }
}

impl_transactional_action!(TxDemoAction);

// ── Runner ─────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    println!("▶ transactional — fake charge(amount=250) through TransactionalAction DX");
    println!();

    let ctx = TestContextBuilder::new().with_input(json!({ "amount": 250 }));
    let report = TestRuntime::new(ctx)
        .run_stateful(TxDemoAction::new())
        .await?;

    println!("kind:       {}", report.kind);
    println!("iterations: {}", report.iterations);
    println!("duration:   {:?}", report.duration);
    if let Some(note) = &report.note {
        println!("note:       {note}");
    }
    println!();
    println!("Committed output:");
    println!("{}", serde_json::to_string_pretty(&report.output)?);

    Ok(())
}
