use nebula_schema::*;

#[test]
fn string_with_date_hint_replaces_datefield() {
    let f = Field::string(FieldKey::new("d").unwrap()).hint(InputHint::Date);
    // key() is a method on StringField generated by the define_field! macro
    assert_eq!(f.key().as_str(), "d");
}

#[test]
fn visibility_never_replaces_hiddenfield() {
    let f = Field::string(FieldKey::new("h").unwrap()).visible(VisibilityMode::Never);
    // visible is a pub field; use field access (no method-call conflict with builder)
    assert!(matches!(f.visible, VisibilityMode::Never));
}

#[test]
fn field_carries_expression_mode() {
    // Field::boolean returns BooleanField; convert to Field to use the enum accessor
    let f: Field = Field::boolean(FieldKey::new("b").unwrap()).into();
    // Boolean defaults to Forbidden
    assert!(matches!(f.expression(), ExpressionMode::Forbidden));
}
