//! Durable JSON-v1 fixtures, independent of the authored/resolved tree codec.
//!
//! Golden hex was captured from the JSON writer used by
//! `FieldValue::Literal(value).canonical_bytes()` at commit
//! `dabd10c0e2ec91dbb65dd55e8df6b8a36baf38d4`, using serde_json 1.0.151.
//! It was not generated by the replacement codec.

use nebula_schema::canonical_json_v1;
use proptest::prelude::*;
use serde_json::{Map, Number, Value, json};

fn assert_golden(name: &str, value: &Value, expected: &str) {
    assert_eq!(
        hex::encode(canonical_json_v1(value).unwrap()),
        expected,
        "JSON-v1 bytes changed for {name}",
    );
}

#[test]
fn scalar_goldens_match_the_original_json_literal_encoder() {
    for (name, value, expected) in [
        (
            "null",
            Value::Null,
            "6e62736368656d612d76616c75652d76000101",
        ),
        (
            "false",
            json!(false),
            "6e62736368656d612d76616c75652d7600010200",
        ),
        (
            "true",
            json!(true),
            "6e62736368656d612d76616c75652d7600010201",
        ),
        (
            "empty_string",
            json!(""),
            "6e62736368656d612d76616c75652d7600010500",
        ),
        (
            "string",
            json!("hello"),
            "6e62736368656d612d76616c75652d760001050568656c6c6f",
        ),
        (
            "unicode_string",
            json!("\u{e9}\u{1f680}\0"),
            "6e62736368656d612d76616c75652d7600010507c3a9f09f9a8000",
        ),
        (
            "expression_string",
            json!("{{ $env.API_KEY }}"),
            "6e62736368656d612d76616c75652d76000105127b7b2024656e762e4150495f4b4559207d7d",
        ),
    ] {
        assert_golden(name, &value, expected);
    }
}

#[test]
fn number_goldens_preserve_v1_integer_and_float_encoding() {
    for (name, value, expected) in [
        (
            "zero",
            json!(0),
            "6e62736368656d612d76616c75652d7600010300000000000000000000000000000000",
        ),
        (
            "negative_zero",
            serde_json::from_str("-0").unwrap(),
            "6e62736368656d612d76616c75652d7600010300000000000000000000000000000000",
        ),
        (
            "negative_zero_float",
            json!(-0.0),
            "6e62736368656d612d76616c75652d7600010300000000000000000000000000000000",
        ),
        (
            "one",
            json!(1),
            "6e62736368656d612d76616c75652d7600010300000000000000000000000000000001",
        ),
        (
            "one_float",
            json!(1.0),
            "6e62736368656d612d76616c75652d7600010300000000000000000000000000000001",
        ),
        (
            "negative_one",
            json!(-1),
            "6e62736368656d612d76616c75652d76000103ffffffffffffffffffffffffffffffff",
        ),
        (
            "fraction",
            json!(1.5),
            "6e62736368656d612d76616c75652d760001043ff8000000000000",
        ),
        (
            "negative_fraction",
            json!(-2.25),
            "6e62736368656d612d76616c75652d76000104c002000000000000",
        ),
        (
            "i64_min",
            json!(i64::MIN),
            "6e62736368656d612d76616c75652d76000103ffffffffffffffff8000000000000000",
        ),
        (
            "i64_max",
            json!(i64::MAX),
            "6e62736368656d612d76616c75652d7600010300000000000000007fffffffffffffff",
        ),
        (
            "u64_max",
            json!(u64::MAX),
            "6e62736368656d612d76616c75652d760001030000000000000000ffffffffffffffff",
        ),
        (
            "i64_min_float",
            json!(-9_223_372_036_854_775_808.0_f64),
            "6e62736368656d612d76616c75652d76000103ffffffffffffffff8000000000000000",
        ),
        (
            "u64_bound_float",
            json!(18_446_744_073_709_551_616.0_f64),
            "6e62736368656d612d76616c75652d7600010300000000000000010000000000000000",
        ),
        (
            "exact_large_float",
            json!(5_000_000_000_000_000_000.0_f64),
            "6e62736368656d612d76616c75652d7600010300000000000000004563918244f40000",
        ),
        (
            "i128_lower_float",
            json!(-2.0_f64.powi(127)),
            "6e62736368656d612d76616c75652d76000104c7e0000000000000",
        ),
        (
            "i128_upper_float",
            json!(2.0_f64.powi(127)),
            "6e62736368656d612d76616c75652d7600010447e0000000000000",
        ),
        (
            "i128_inside_float",
            json!(f64::from_bits(2.0_f64.powi(127).to_bits() - 1)),
            "6e62736368656d612d76616c75652d760001037ffffffffffffc000000000000000000",
        ),
        (
            "min_subnormal",
            Value::Number(Number::from_f64(f64::from_bits(1)).unwrap()),
            "6e62736368656d612d76616c75652d760001040000000000000001",
        ),
        (
            "negative_min_subnormal",
            json!(-f64::from_bits(1)),
            "6e62736368656d612d76616c75652d760001048000000000000001",
        ),
        (
            "max_finite_float",
            json!(f64::MAX),
            "6e62736368656d612d76616c75652d760001047fefffffffffffff",
        ),
        (
            "min_finite_float",
            json!(f64::MIN),
            "6e62736368656d612d76616c75652d76000104ffefffffffffffff",
        ),
    ] {
        assert_golden(name, &value, expected);
    }
}

#[test]
fn container_goldens_preserve_raw_json_tags_and_data() {
    for (name, value, expected) in [
        (
            "empty_array",
            json!([]),
            "6e62736368656d612d76616c75652d7600010b00",
        ),
        (
            "array",
            json!([null, false, true, 1, 1.5, "x", [], {}]),
            concat!(
                "6e62736368656d612d76616c75652d7600010b0801020002010300000000000000000000000000000001043f",
                "f80000000000000501780b000c00",
            ),
        ),
        (
            "empty_object",
            json!({}),
            "6e62736368656d612d76616c75652d7600010c00",
        ),
        (
            "simple_object",
            json!({"a": 1}),
            "6e62736368656d612d76616c75652d7600010c0101610300000000000000000000000000000001",
        ),
        (
            "nested",
            json!({"z": [{"b": 2, "a": 1}], "a": {"n": null}}),
            concat!(
                "6e62736368656d612d76616c75652d7600010c0201610c01016e01017a0b010c020161030000000000000000",
                "000000000000000101620300000000000000000000000000000002",
            ),
        ),
        (
            "arbitrary_keys",
            json!({"": 0, "/": 1, "~": 2, "a/b": 3, "not a key": 4, "a.b": 5, "\u{e9}": 6, "\u{1f680}": 7, "\0": 8}),
            concat!(
                "6e62736368656d612d76616c75652d7600010c09000300000000000000000000000000000000010003000000",
                "00000000000000000000000008012f030000000000000000000000000000000103612e620300000000000000",
                "00000000000000000503612f620300000000000000000000000000000003096e6f742061206b657903000000",
                "00000000000000000000000004017e030000000000000000000000000000000202c3a9030000000000000000",
                "000000000000000604f09f9a800300000000000000000000000000000007",
            ),
        ),
        (
            "authored_looking_object",
            json!({"$expr": "{{ $env.API_KEY }}", "kind": "expression", "value": "$data.x"}),
            concat!(
                "6e62736368656d612d76616c75652d7600010c0305246578707205127b7b2024656e762e4150495f4b455920",
                "7d7d046b696e64050a65787072657373696f6e0576616c7565050724646174612e78",
            ),
        ),
        (
            "mode_looking_object",
            json!({"mode": "manual", "value": {"x": 1}}),
            concat!(
                "6e62736368656d612d76616c75652d7600010c02046d6f646505066d616e75616c0576616c75650c01017803",
                "00000000000000000000000000000001",
            ),
        ),
    ] {
        assert_golden(name, &value, expected);
    }
}

#[test]
fn integer_normalization_is_exact_not_lossy_float_coercion() {
    for spelling in ["1", "1.0", "1e0", "1.000e+0"] {
        let number: Value = serde_json::from_str(spelling).unwrap();
        assert_eq!(
            canonical_json_v1(&number).unwrap(),
            canonical_json_v1(&json!(1)).unwrap()
        );
    }
    for spelling in ["0", "-0", "0.0", "-0.0", "0e0", "-0e0"] {
        let number: Value = serde_json::from_str(spelling).unwrap();
        assert_eq!(
            canonical_json_v1(&number).unwrap(),
            canonical_json_v1(&json!(0)).unwrap()
        );
    }
    for (exact, rounded) in [
        (
            json!(9_007_199_254_740_993_u64),
            json!(9_007_199_254_740_992.0_f64),
        ),
        (json!(i64::MAX), json!(9_223_372_036_854_775_808.0_f64)),
        (json!(u64::MAX), json!(18_446_744_073_709_551_616.0_f64)),
    ] {
        assert_ne!(
            canonical_json_v1(&exact).unwrap(),
            canonical_json_v1(&rounded).unwrap()
        );
    }
}

#[test]
fn nested_key_permutation_preserves_the_entire_encoding() {
    let forward: Value = serde_json::from_str(r#"{"z":[{"b":2,"a":1}],"a":{"n":null}}"#).unwrap();
    let reversed: Value = serde_json::from_str(r#"{"a":{"n":null},"z":[{"a":1,"b":2}]}"#).unwrap();
    assert_eq!(
        canonical_json_v1(&forward).unwrap(),
        canonical_json_v1(&reversed).unwrap()
    );
}

#[test]
fn utf8_is_not_normalized_and_empty_keys_are_not_omitted() {
    assert_ne!(
        canonical_json_v1(&json!({"\u{e9}": 1})).unwrap(),
        canonical_json_v1(&json!({"e\u{301}": 1})).unwrap(),
    );
    assert_ne!(
        canonical_json_v1(&json!({"": null})).unwrap(),
        canonical_json_v1(&json!({})).unwrap(),
    );
    assert_ne!(
        canonical_json_v1(&json!({"/": null})).unwrap(),
        canonical_json_v1(&json!({"~1": null})).unwrap(),
    );
}

#[test]
fn v1_length_prefixes_use_unsigned_leb128_for_bytes_and_counts() {
    for (length, prefix) in [
        (127, vec![0x7f]),
        (128, vec![0x80, 0x01]),
        (16_384, vec![0x80, 0x80, 0x01]),
    ] {
        let text = "x".repeat(length);
        let mut expected = b"nbschema-value-v\x00\x01\x05".to_vec();
        expected.extend_from_slice(&prefix);
        expected.extend_from_slice(text.as_bytes());
        assert_eq!(canonical_json_v1(&json!(text)).unwrap(), expected);

        let mut expected = b"nbschema-value-v\x00\x01\x0b".to_vec();
        expected.extend_from_slice(&prefix);
        expected.extend(std::iter::repeat_n(0x01, length));
        assert_eq!(
            canonical_json_v1(&Value::Array(vec![Value::Null; length])).unwrap(),
            expected
        );

        let mut expected = b"nbschema-value-v\x00\x01\x0c\x01".to_vec();
        expected.extend_from_slice(&prefix);
        expected.extend_from_slice(text.as_bytes());
        expected.push(0x01);
        assert_eq!(canonical_json_v1(&json!({text: null})).unwrap(), expected);
    }

    let object: Map<String, Value> = (0..128)
        .map(|index| (format!("{index:03}"), Value::Null))
        .collect();
    let mut expected = b"nbschema-value-v\x00\x01\x0c\x80\x01".to_vec();
    for index in 0..128 {
        expected.push(0x03);
        expected.extend_from_slice(format!("{index:03}").as_bytes());
        expected.push(0x01);
    }
    assert_eq!(canonical_json_v1(&Value::Object(object)).unwrap(), expected);
}

#[test]
fn json_arrays_retain_order_and_length_delimiters_are_unambiguous() {
    for (left, right) in [
        (json!([1, 2]), json!([2, 1])),
        (json!(["ab", "c"]), json!(["a", "bc"])),
        (json!({"ab": "c"}), json!({"a": "bc"})),
        (json!([null]), json!({"": null})),
    ] {
        assert_ne!(
            canonical_json_v1(&left).unwrap(),
            canonical_json_v1(&right).unwrap()
        );
    }
}

#[test]
fn the_v1_depth_limit_keeps_root_at_zero_and_rejects_depth_65() {
    let mut nested = Value::Null;
    let mut expected = b"nbschema-value-v\x00\x01".to_vec();
    for _ in 0..32 {
        nested = json!({"": [nested]});
        expected.extend_from_slice(&[0x0c, 0x01, 0x00, 0x0b, 0x01]);
    }
    expected.push(0x01);
    assert_eq!(canonical_json_v1(&nested).unwrap(), expected);

    let over_limit = json!([nested]);
    let error = canonical_json_v1(&over_limit).unwrap_err();
    assert_eq!(error.code(), "recursion_limit");
    assert_eq!(
        error.message(),
        "value nesting exceeds the maximum canonicalization depth"
    );
}

#[test]
fn empty_containers_at_depth_64_remain_encodable() {
    for (mut nested, tag) in [(json!([]), 0x0b), (json!({}), 0x0c)] {
        let mut expected = b"nbschema-value-v\x00\x01".to_vec();
        for _ in 0..64 {
            nested = json!([nested]);
            expected.extend_from_slice(&[0x0b, 0x01]);
        }
        expected.extend_from_slice(&[tag, 0x00]);
        assert_eq!(canonical_json_v1(&nested).unwrap(), expected);
        assert_eq!(
            canonical_json_v1(&json!([nested])).unwrap_err().code(),
            "recursion_limit"
        );
    }
}

fn json_data() -> impl Strategy<Value = Value> {
    prop_oneof![
        Just(Value::Null),
        any::<bool>().prop_map(Value::Bool),
        any::<i64>().prop_map(|number| Value::Number(number.into())),
        any::<u64>().prop_map(|number| Value::Number(number.into())),
        any::<f64>().prop_filter_map("JSON numbers are finite", |number| Number::from_f64(number)
            .map(Value::Number)),
        any::<String>().prop_map(Value::String),
    ]
    .prop_recursive(4, 64, 8, |inner| {
        prop_oneof![
            proptest::collection::vec(inner.clone(), 0..8).prop_map(Value::Array),
            proptest::collection::btree_map(any::<String>(), inner, 0..8)
                .prop_map(|entries| Value::Object(entries.into_iter().collect())),
        ]
    })
}

fn reverse_object_entries(value: &Value) -> Value {
    match value {
        Value::Object(entries) => Value::Object(
            entries
                .iter()
                .rev()
                .map(|(key, value)| (key.clone(), reverse_object_entries(value)))
                .collect(),
        ),
        Value::Array(items) => Value::Array(items.iter().map(reverse_object_entries).collect()),
        _ => value.clone(),
    }
}

proptest! {
    #[test]
    fn every_object_level_is_independent_of_insertion_order(value in json_data()) {
        let reversed = reverse_object_entries(&value);
        prop_assert_eq!(canonical_json_v1(&value).unwrap(), canonical_json_v1(&reversed).unwrap());
    }

    #[test]
    fn exactly_representable_integers_share_bytes_with_floats(number in any::<i32>()) {
        prop_assert_eq!(
            canonical_json_v1(&json!(number)).unwrap(),
            canonical_json_v1(&json!(f64::from(number))).unwrap(),
        );
    }
}
