-- 0028: Plane-A OAuth PKCE state
-- Layer: Identity
-- Spec: 03 (identity-auth)
--
-- Server-side storage for the Plane-A sign-in-with-OAuth flow. Each
-- `start_oauth` mints a row keyed by the random `state` value; the
-- matching `complete_oauth` consumes the row atomically to recover the
-- PKCE `code_verifier` and validate the callback. The `state` value is
-- generated by the API layer (CSPRNG, url-safe base64) and is NOT a
-- ULID, so the primary key is TEXT.
--
-- Named `plane_a_oauth_states` to avoid clashing with the Plane-B
-- credential OAuth pending-state surface (`pending_credentials` in
-- the `0008_credentials.sql` family).

CREATE TABLE plane_a_oauth_states (
    state          TEXT PRIMARY KEY,
    provider       TEXT NOT NULL,
    code_verifier  TEXT NOT NULL,
    redirect_uri   TEXT,
    created_at     TIMESTAMPTZ NOT NULL,
    expires_at     TIMESTAMPTZ NOT NULL,
    consumed_at    TIMESTAMPTZ
);

-- Cleanup sweep: find expired, never-consumed rows for deletion.
CREATE INDEX idx_plane_a_oauth_states_cleanup
    ON plane_a_oauth_states (expires_at)
    WHERE consumed_at IS NULL;
