//! Task queue interface and in-memory implementation.
//!
//! Used to distribute work to workers; at-least-once delivery with ack/nack.

use std::{
    collections::HashMap,
    sync::{
        Arc,
        atomic::{AtomicUsize, Ordering},
    },
    time::Duration,
};

use async_trait::async_trait;
use thiserror::Error;
use tokio::{
    sync::{Mutex, mpsc},
    time::Instant,
};

/// Errors returned by queue operations.
#[derive(Debug, Error)]
pub enum QueueError {
    /// Task not found (e.g. ack/nack unknown id).
    #[error("{entity} not found: {id}")]
    NotFound {
        /// Entity type (for example, `task`).
        entity: String,
        /// Missing entity identifier.
        id: String,
    },

    /// Internal queue failure (full, closed, etc.).
    #[error("internal error: {0}")]
    Internal(String),
}

impl QueueError {
    /// Convenience constructor for [`QueueError::NotFound`].
    pub fn not_found(entity: impl Into<String>, id: impl Into<String>) -> Self {
        Self::NotFound {
            entity: entity.into(),
            id: id.into(),
        }
    }
}

/// Work queue interface for distributing tasks to workers.
///
/// At-least-once semantics: enqueue → dequeue → ack (or nack to requeue).
#[async_trait]
pub trait TaskQueue: Send + Sync {
    /// Enqueue a task. Returns a task ID.
    async fn enqueue(&self, payload: serde_json::Value) -> Result<String, QueueError>;

    /// Dequeue the next available task.
    ///
    /// Distinguishes timeout from a closed queue so callers can react
    /// differently to "no work yet" vs "producer is gone".
    async fn dequeue(&self, timeout: Duration) -> Result<DequeueResult, QueueError>;

    /// Acknowledge successful processing.
    async fn ack(&self, task_id: &str) -> Result<(), QueueError>;

    /// Negative-acknowledge — requeue for retry.
    async fn nack(&self, task_id: &str) -> Result<(), QueueError>;

    /// Total number of tasks tracked by the queue: queued + in-flight.
    ///
    /// This is a workload cardinality view, not just channel depth.
    async fn len(&self) -> Result<usize, QueueError>;

    /// Number of tasks currently waiting in the queue channel.
    async fn queued_len(&self) -> Result<usize, QueueError>;

    /// Number of tasks currently leased to workers and awaiting ack/nack.
    async fn in_flight_len(&self) -> Result<usize, QueueError>;

    /// Whether the queue is empty.
    async fn is_empty(&self) -> Result<bool, QueueError> {
        Ok(self.len().await? == 0)
    }
}

/// Outcome of a dequeue attempt.
#[derive(Debug, Clone, PartialEq)]
pub enum DequeueResult {
    /// A task was successfully leased to a worker.
    Item {
        /// Task ID generated by enqueue.
        task_id: String,
        /// Opaque payload for worker execution.
        payload: serde_json::Value,
    },
    /// No item arrived before the timeout elapsed.
    Timeout,
    /// Queue is closed and cannot deliver more items.
    Closed,
}

#[derive(Debug, Clone)]
struct QueueItem {
    id: String,
    payload: serde_json::Value,
}

#[derive(Debug, Clone)]
struct InFlightEntry {
    item: QueueItem,
    lease_deadline: Instant,
}

/// In-memory bounded task queue.
///
/// Tasks: Queued → In-flight (dequeued) → Done (acked) or requeued (nacked).
pub struct MemoryQueue {
    sender: mpsc::Sender<QueueItem>,
    receiver: Arc<Mutex<mpsc::Receiver<QueueItem>>>,
    in_flight: Arc<Mutex<HashMap<String, InFlightEntry>>>,
    queued_count: AtomicUsize,
    visibility_timeout: Duration,
}

impl MemoryQueue {
    const DEFAULT_VISIBILITY_TIMEOUT: Duration = Duration::from_secs(30);

    /// Create a new memory queue with the given capacity.
    #[must_use]
    pub fn new(capacity: usize) -> Self {
        Self::new_with_visibility_timeout(capacity, Self::DEFAULT_VISIBILITY_TIMEOUT)
    }

    /// Create a new memory queue with an explicit visibility timeout.
    ///
    /// A dequeued task must be acknowledged within this timeout; otherwise it
    /// is considered stale and can be redelivered by a later [`TaskQueue::dequeue`].
    #[must_use]
    pub fn new_with_visibility_timeout(capacity: usize, visibility_timeout: Duration) -> Self {
        let (sender, receiver) = mpsc::channel(capacity);
        Self {
            sender,
            receiver: Arc::new(Mutex::new(receiver)),
            in_flight: Arc::new(Mutex::new(HashMap::new())),
            queued_count: AtomicUsize::new(0),
            visibility_timeout,
        }
    }

    async fn try_reclaim_stale_in_flight(&self) -> Option<QueueItem> {
        let now = Instant::now();
        let mut in_flight = self.in_flight.lock().await;
        let stale_task_id = in_flight
            .iter()
            .find(|(_, entry)| entry.lease_deadline <= now)
            .map(|(task_id, _)| task_id.clone())?;
        in_flight.remove(&stale_task_id).map(|entry| entry.item)
    }

    async fn lease_item(&self, item: QueueItem) -> (String, serde_json::Value) {
        let id = item.id.clone();
        let payload = item.payload.clone();
        let lease_deadline = Instant::now() + self.visibility_timeout;
        self.in_flight.lock().await.insert(
            id.clone(),
            InFlightEntry {
                item,
                lease_deadline,
            },
        );
        (id, payload)
    }
}

#[async_trait]
impl TaskQueue for MemoryQueue {
    async fn enqueue(&self, payload: serde_json::Value) -> Result<String, QueueError> {
        let id = uuid::Uuid::new_v4().to_string();
        let item = QueueItem {
            id: id.clone(),
            payload,
        };
        self.sender
            .try_send(item)
            .map_err(|e| QueueError::Internal(format!("queue full or closed: {e}")))?;
        self.queued_count.fetch_add(1, Ordering::Relaxed);
        Ok(id)
    }

    async fn dequeue(&self, timeout: Duration) -> Result<DequeueResult, QueueError> {
        if let Some(item) = self.try_reclaim_stale_in_flight().await {
            let (task_id, payload) = self.lease_item(item).await;
            return Ok(DequeueResult::Item { task_id, payload });
        }

        let mut rx = self.receiver.lock().await;
        let result = tokio::time::timeout(timeout, rx.recv()).await;
        match result {
            Ok(Some(item)) => {
                self.queued_count.fetch_sub(1, Ordering::Relaxed);
                let (task_id, payload) = self.lease_item(item).await;
                Ok(DequeueResult::Item { task_id, payload })
            },
            Ok(None) => Ok(DequeueResult::Closed),
            Err(_) => Ok(DequeueResult::Timeout),
        }
    }

    async fn ack(&self, task_id: &str) -> Result<(), QueueError> {
        let removed = self.in_flight.lock().await.remove(task_id);
        if removed.is_none() {
            return Err(QueueError::not_found("Task", task_id));
        }
        Ok(())
    }

    async fn nack(&self, task_id: &str) -> Result<(), QueueError> {
        // Keep the item in-flight until requeue succeeds to preserve
        // at-least-once guarantees when the queue is saturated.
        let item = {
            let in_flight = self.in_flight.lock().await;
            in_flight.get(task_id).map(|entry| entry.item.clone())
        };
        let Some(item) = item else {
            return Err(QueueError::not_found("Task", task_id));
        };

        self.sender
            .send(item)
            .await
            .map_err(|e| QueueError::Internal(format!("requeue failed: {e}")))?;
        self.queued_count.fetch_add(1, Ordering::Relaxed);
        let _ = self.in_flight.lock().await.remove(task_id);
        Ok(())
    }

    async fn len(&self) -> Result<usize, QueueError> {
        Ok(self.queued_count() + self.in_flight_count().await)
    }

    async fn queued_len(&self) -> Result<usize, QueueError> {
        Ok(self.queued_count())
    }

    async fn in_flight_len(&self) -> Result<usize, QueueError> {
        Ok(self.in_flight_count().await)
    }
}

impl MemoryQueue {
    fn queued_count(&self) -> usize {
        self.queued_count.load(Ordering::Relaxed)
    }

    async fn in_flight_count(&self) -> usize {
        self.in_flight.lock().await.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn dequeue_reports_timeout_distinct_from_closed() {
        let queue = MemoryQueue::new(1);
        let got = queue.dequeue(Duration::from_millis(10)).await.unwrap();
        assert_eq!(got, DequeueResult::Timeout);
    }

    #[tokio::test]
    async fn len_includes_in_flight_work() {
        let queue = MemoryQueue::new(2);
        let id = queue
            .enqueue(serde_json::json!({"task":"x"}))
            .await
            .unwrap();
        assert_eq!(queue.len().await.unwrap(), 1);
        assert_eq!(queue.queued_len().await.unwrap(), 1);
        assert_eq!(queue.in_flight_len().await.unwrap(), 0);

        let got = queue.dequeue(Duration::from_millis(50)).await.unwrap();
        assert!(matches!(
            got,
            DequeueResult::Item { task_id, .. } if task_id == id
        ));
        // Still one unit of work, but now leased.
        assert_eq!(queue.len().await.unwrap(), 1);
        assert_eq!(queue.queued_len().await.unwrap(), 0);
        assert_eq!(queue.in_flight_len().await.unwrap(), 1);
    }

    #[tokio::test]
    async fn nack_waits_for_capacity_and_preserves_task() {
        let queue = Arc::new(MemoryQueue::new(1));

        let first_id = queue
            .enqueue(serde_json::json!({"task":"first"}))
            .await
            .unwrap();
        let (dequeued_id, _) = match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
            DequeueResult::Item { task_id, payload } => (task_id, payload),
            other => panic!("expected dequeued task, got {other:?}"),
        };
        assert_eq!(dequeued_id, first_id);

        // Fill the queue so nack must wait for capacity.
        queue
            .enqueue(serde_json::json!({"task":"filler"}))
            .await
            .unwrap();

        let queue_for_nack = Arc::clone(&queue);
        let id_for_nack = dequeued_id.clone();
        let nack_task = tokio::spawn(async move { queue_for_nack.nack(&id_for_nack).await });

        tokio::time::sleep(Duration::from_millis(20)).await;
        assert!(
            !nack_task.is_finished(),
            "nack should block while queue is full"
        );

        // Free one slot, then nack should complete and requeue original task.
        let (_filler_id, _filler_payload) =
            match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
                DequeueResult::Item { task_id, payload } => (task_id, payload),
                other => panic!("expected filler dequeue, got {other:?}"),
            };
        nack_task.await.unwrap().unwrap();

        let (requeued_id, _) = match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
            DequeueResult::Item { task_id, payload } => (task_id, payload),
            other => panic!("expected requeued task, got {other:?}"),
        };
        assert_eq!(requeued_id, dequeued_id);
    }

    #[tokio::test]
    async fn stale_in_flight_task_is_redelivered() {
        let queue = MemoryQueue::new_with_visibility_timeout(1, Duration::from_millis(20));
        let id = queue
            .enqueue(serde_json::json!({"task":"stale"}))
            .await
            .unwrap();
        let (first_delivery, _) = match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
            DequeueResult::Item { task_id, payload } => (task_id, payload),
            other => panic!("expected first delivery, got {other:?}"),
        };
        assert_eq!(first_delivery, id);

        tokio::time::sleep(Duration::from_millis(30)).await;

        let (second_delivery, _) = match queue.dequeue(Duration::from_millis(50)).await.unwrap() {
            DequeueResult::Item { task_id, payload } => (task_id, payload),
            other => panic!("expected stale redelivery, got {other:?}"),
        };
        assert_eq!(second_delivery, id);
    }
}
