name: CODEOWNERS

on:
  pull_request:
    paths:
      - '.github/CODEOWNERS'

permissions:
  contents: read

jobs:
  validate:
    name: Validate CODEOWNERS
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate CODEOWNERS
        uses: mszostok/codeowners-validator@7f3f5e28c6d7b8dfae5731e54ce2272ca384592f # v0.7.4
        with:
          checks: "files,duppatterns,syntax"
          experimental_checks: "avoid-shadowing,no-unowned-patterns"
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
