[package]
name = "nebula-error"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Centralized error handling system for Nebula workflow engine"
keywords.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
# Async traits
async-trait = { workspace = true }

# Error handling
anyhow = { version = "1.0.99", features = ["backtrace"] }
thiserror = { version = "2.0.16" }

# Random number generation
rand = "0.8"

# Serialization
bincode = "1.3"
serde = { workspace = true }
serde_json = "1.0"

# Time handling
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["time"] }

# UUID generation
uuid = { workspace = true, features = ["v4", "serde"] }

[dev-dependencies]
# Testing
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-test = "0.4"

# Benchmarking
criterion = { version = "0.5", features = ["html_reports"] }

# Use workspace lints configuration
[lints]
workspace = true

[[bench]]
name = "error_creation"
harness = false
