[package]
name = "nebula-error"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Centralized error handling system for Nebula workflow engine"
keywords.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
# Error handling
thiserror = { workspace = true }
anyhow = "1.0"

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# UUID generation
uuid = { workspace = true, features = ["v4", "serde"] }

# Async traits
async-trait = "0.1"

# Time handling
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["time"] }

# Random number generation
rand = "0.8"

# Collections
dashmap = "5.5"

[dev-dependencies]
# Testing
tokio = { workspace = true, features = ["full"] }
tokio-test = "0.4"
pretty_assertions = { workspace = true }
