//! Credential metadata — static type descriptors and runtime operational state.
//!
//! [`CredentialMetadata`] is the static integration-catalog descriptor
//! (auto-generated by `#[derive(Credential)]`). [`CredentialRecord`] is the
//! non-sensitive runtime operational state (timestamps, version, tags).
//! [`CredentialKey`] is the newtype key for the runtime registry.
//!
//! # Canonical import paths
//!
//! This submodule is `pub` for escape hatches. Prefer flat root re-exports:
//! `use nebula_credential::CredentialMetadata;`
//! (not `nebula_credential::metadata::CredentialMetadata`).

mod key;
#[allow(clippy::module_inception)]
mod metadata;
mod record;

pub use key::CredentialKey;
pub use metadata::{
    CredentialMetadata, CredentialMetadataBuildError, CredentialMetadataBuilder,
    MetadataCompatibilityError,
};
pub use record::CredentialRecord;
